README.md

Sampling and sim-based-inference links are wrong, quick fix.

Fixing links in readme

---

outlines/models/hf_diffusers.py
outlines/models/hf_transformers.py

Add support for mps backend to optimize inference on Apple Silicon

Add mps backend for Pytorch in HF models

---

docs/source/index.rst

Update development statement

---

outlines/text/functions.py
outlines/text/prompts.py

This PR add some minor updates to support Pydantic 2.0.

Updates for Pydantic 2.0

---

outlines/text/generate/continuation.py
outlines/text/generate/regex.py

This is a quick fix for use of a GPU with `Continuation` and `Regex`.

Make sure `Continuation` and `Regex` use the correct device

---

pyproject.toml

Workflow to publish on PyPi fails: https://github.com/normal-computing/outlines/actions/runs/5603177911/jobs/10249420782

Add missing requirements

---

outlines/models/openai.py

Fix error when using type="float" on OpenAI model

---

README.md

Just a fix for a copy pasta. @mlelarge

Fix ReAct example link path

---

pyproject.toml

Explicitly list the packages in modules

---

README.md

Rename `agent` function to `my_commands`.

Fix non-matching function definition and call

---

README.md

Hi to whoever is reading this! 🤗 
This is a simple PR to just remove an import in the `README.md` which is not needed.
Thanks!

Remove unused `from typing import List` in `README.md`

---

outlines/models/transformers.py
tests/models/test_transformers.py

More HF Llama tokenizer space fixes

---

pyproject.toml

Add `py.typed` and package data information

---

.github/workflows/tests.yml
outlines/text/json_schema.py
outlines/text/parsing.py
outlines/text/prompts.py
pyproject.toml

This should allow the use of Python versions 3.8 and up.

Refactor for Python 3.8-3.9 compatibility

---

examples/sampling.ipynb

If I'm 6 and my sister is half my age, this means she's 3. 64 years later, when I'm 70, my sister is going to be 67, as her age isn't always my age divided by 2.

Fix math error in sampling example

---

README.md
docs/get_started.md

Mention in README `datasets` requirement

---

outlines/models/__init__.py
outlines/models/awq.py
outlines/models/gptq.py
outlines/models/transformers.py
outlines/text/generate/sequence.py
pyproject.toml
tests/models/test_transformers.py
tests/text/generate/test_integration_transfomers.py
tests/text/test_fsm.py

Add integration for `AutoGPTQ` and `AutoAWQ`

---

README.md
docs/get_started.md
outlines/generate/generator.py
outlines/models/__init__.py
outlines/models/mamba.py
pyproject.toml

Code: https://github.com/state-spaces/mamba
ArXiv: https://arxiv.org/abs/2312.00752

Add Mamba models

---

examples/math_generate_code.py
outlines/models/openai.py

The `vectorize` decorator was not updated in #388. This PR fixes this and caches the generation at a more appropriate place. Fixes #429

Fix `vectorize` signature and caching in OpenAI integration

---

outlines/generate/generator.py

Came across this library recently, was reading bits of the source code, thought this could be simplified a bit

Simplify logit biasing logic

---

outlines/caching.py

Fix typo in caching.py

---

outlines/models/openai.py
tests/models/test_openai.py

Use the OpenAI API to check that a model exists

---

docs/reference/vllm.md
outlines/serve/serve.py
outlines/serve/vllm.py

Reverts outlines-dev/outlines#517 This has introduced bugs in the vLLM serving more generally #535 #536

Revert "Add CFG to vllm serving"

---

outlines/prompts.py

HAL will eliminate anyone not fit for the mission! :)

Fix typo in prompt example

---

outlines/fsm/fsm.py
tests/fsm/test_fsm.py

Fixes https://github.com/outlines-dev/outlines/issues/565

allow generation of %ignore terminals

---

docs/reference/samplers.md
outlines/samplers.py
tests/test_samplers.py

Add `top_p` logits processor and `temperature` rescaling to the multinomial sampler

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

https://github.com/outlines-dev/outlines/issues/776

allow json ints to be negative

---

outlines/models/openai.py

Add `model_name` as an optional parameter for `azure_openai`

---

docs/reference/models/openai.md

Make the code render as Python.

fix code rendering

---

docs/welcome.md

Correct the link for llamacpp library.

Correct link for llamacpp library

---

docs/reference/models/tgi.md
mkdocs.yml

Add link to TGI documentation

---

docs/welcome.md
mkdocs.yml
requirements-doc.txt

This Pull Request adds the following to the documentation
- An image that shows all the repository contributors (thank you!)
- The creation and last update date for each page
- The authors of a given page in the documentation

Add contributors, creation and update date

---

docs/cookbook/qa-with-citations.md
mkdocs.yml

As requested by @rlouf this PR adds a question answering with citations example to the Cookbook using llama-cpp-python.

Add QA with Citations example to the Cookbook

---

docs/reference/models/vllm.md

Correct the name for autoawq on PyPI (for lazy copy-pasting...)

fix PyPI name for autoawq

---

docs/cookbook/qa-with-citations.md

- Correct link for llama-cpp-python
- Add installation instructions for llama-cpp-python
- Correct first question-answer

Correct link and add llama-cpp-python installation instructions

---

docs/cookbook/index.md

Add links to the two examples:
- Q&A with Citations
- Knowledge Graph Generation

Add links to the two examples

---

docs/community/examples.md

This PR adds link to Multimodal Structured Generation (MMSG) library to docs.
@lapp0 @rlouf

Add link to Multimodal Structured Generation (MMSG) library to docs

---

outlines/caching.py

Correct the documentation to disable caching

Correct the documentation to disable caching

---

docs/reference/models/mlxlm.md

Fixes #986
Rendered https://github.com/lapp0/outlines/blob/improve-mlx-lm-docs/docs/reference/models/mlxlm.md
Includes more details about model parameters, links more resources, and provides more examples.

More detailed mlxlm documentation

---

docs/cookbook/chain_of_thought.md
docs/cookbook/index.md
mkdocs.yml

As [requested](https://x.com/OutlinesOSS/status/1821280741550174260), I'm adding the chain of though as structured output example. I have pre-commited locally and added the links to the index and to the mkdocs.yml and to the /docs/cookbook/index.md

Add chain of thought example

---

pyproject.toml

Fix coverage `exclude_lines` setting for ellipsis

---

docs/cookbook/index.md
docs/cookbook/react_agent.md
mkdocs.yml

As [requested](https://x.com/OutlinesOSS/status/1822242455300747586), I'm adding the ReAct agent with structured outputs example. I have pre-commited locally and added the links to the mkdocs.yml and to the /docs/cookbook/index.md

Add ReAct agent example

---

docs/cookbook/chain_of_thought.md

`schema` here was not defined, so I corrected it to match the appropriate variable.

Correct variable name in chain-of-thought example

---

.github/workflows/tests.yml
pyproject.toml

Use relative coverage source paths

---

docs/reference/serve/vllm.md

A few important guidelines and requirements before we can merge your PR:
Consider opening a **Draft PR** if your work is still in progress but you would
like some feedback from other contributors.
[issues]: https://github.com/outlines-dev/outlines/issues
[git-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[docstring-guidelines]: https://numpydoc.readthedocs.io/en/latest/format.html

docs: fix typo

---

.github/workflows/tests.yml

This should fix some recent issues due to Actions updates.

Include hidden files in coverage CI upload

---

.github/ISSUE_TEMPLATE/doc_request.md
README.md

Didn't see a good issue template to add documentation requests, here's a simple one.

Add documentation request issue template

---

README.md

The account is going to be deactivated soon.

Remove link to Outlines twitter account

---

.github/workflows/asv_benchmark_pr.yml

Fix benchmark workflow triggers

---

pyproject.toml

Pin `outlines-core` version

---

docs/reference/models/llamacpp.md

Minor missing comma in a code example.

add missing comma in llamacpp docs

---

docs/reference/serve/lmstudio.md

Adds docs to get people up and running with the LM Studio structured generation endpoint.

Add docs on serving with LM Studio

---

docs/reference/models/llamacpp.md

docs: update llamacpp.md

---

docs/cookbook/index.md
docs/cookbook/read-pdfs.md
mkdocs.yml

Adds a cookbook on extracting structured output from PDFs.
I included some extra bells and whistles here by showing how to do JSON, regex, and `choice`, which should help provide inspiration to people working with PDFs.

Add PDF cookbook

---

outlines/fsm/guide.py
tests/fsm/test_guide.py
tests/generate/test_integration_llamacpp.py
tests/generate/test_integration_transformers.py

Closes #1274
Caching process will be reconsidered later.

Turn off guide caching

---

README.md

We have a lot of interesting content in there, let's share it!

Add link to YT channel and .txt blog

---

pyproject.toml

This brings some performance improvements for compilation.

Bump outlines-core to 0.1.24

---

examples/vllm_integration.py

Fix JSON structured import

---

docs/reference/generation/json.md
outlines/generate/json.py
pyproject.toml
tests/generate/test_generate.py

This PR aims at integrating support of the `genson` package (in `generate.json`) to be able to use dynamic json schema generation as proposed in #1383.

Add `genson` integration for json generation

---

docs/reference/models/openai.md

Fix documentation error #1426

---

.github/workflows/tests_nightly.yml

Addresses issue #1245 
We would need to add the following 5 secrets to the environment for it to work:
- OPENAI_API_KEY
- ANTHROPIC_API_KEY
- GEMINI_API_KEY
- DOTTXT_API_KEY
- SLACK_TESTS_ERRORS_WEBHOOK_URL

Create nightly tests run in Github actions

---

outlines/types/dsl.py
tests/types/test_dsl.py

Add `from_file` class methods to CFG and JsonSchema

---

docs/cookbook/atomic_caption.md
docs/cookbook/chain_of_density.md
docs/cookbook/chain_of_thought.md
docs/cookbook/classification.md
docs/cookbook/dating_profiles.md
docs/cookbook/deploy-using-bentoml.md
docs/cookbook/deploy-using-cerebrium.md
docs/cookbook/deploy-using-modal.md
docs/cookbook/earnings-reports.md
docs/cookbook/extract_event_details.md
docs/cookbook/extract_event_details.py
docs/cookbook/extraction.md
docs/cookbook/index.md
docs/cookbook/knowledge_graph_extraction.md
docs/cookbook/models_playing_chess.md
docs/cookbook/prompt_templates/chain_of_density.txt
docs/cookbook/prompt_templates/classification.txt
docs/cookbook/prompt_templates/react_agent.txt
docs/cookbook/prompt_templates/simtom_prospective_taking.txt
docs/cookbook/prompt_templates/simtom_simulation.txt
docs/cookbook/qa-with-citations.md
docs/cookbook/react_agent.md
docs/cookbook/read-pdfs.md
docs/cookbook/receipt-digitization.md
docs/cookbook/simtom.md
docs/cookbook/structured_generation_workflow.md

The objective of this PR is to update the content of the `cookbook` directory to make sure all files in it are using the v1 interface of Outlines and are running without errors. This does not imply that the cookbooks are still considered relevant, this matter is left for a future PR.

Update the cookbooks to use v1 interface

---

README.md

Add commerical/contact info for .txt

---

docs/reference/models/tgi.md
outlines/__init__.py
outlines/models/__init__.py
outlines/models/tgi.py
tests/models/test_tgi.py
tests/models/test_tgi_model_adapter.py
tests/test_utils/mock_openai_client.py
tests/test_utils/mock_tgi_client.py
tests/test_utils/utils.py

Addresses #1552 
I've ran the tests with a real TGI server running locally.

Create the TGI model

---

docs/reference/models/sglang.md
outlines/__init__.py
outlines/models/__init__.py
outlines/models/sglang.py
tests/models/test_sglang.py
tests/models/test_sglang_type_adapter.py
tests/test_utils/mock_openai_client.py

Addresses #1553
I've ran the tests with a real SgLang server running locally.

Create the SgLang model

---

docs/index.md
mkdocs.yml

Adding misc improvements as I go

Doc improvements

---

docs/features/models/vllm.md
tests/models/test_vllm.py

Add testing and documentation for vision input for VLLM model

---

docs/features/core/output_types.md
outlines/models/gemini.py
outlines/types/__init__.py
outlines/types/dsl.py
outlines/types/utils.py
tests/models/test_gemini.py
tests/types/test_dsl.py
tests/types/test_to_regex.py
tests/types/test_types_utils.py

Create Choice output type

---

docs/features/advanced/logits_processors.md
docs/features/core/generator.md
docs/features/core/output_types.md
docs/features/index.md
docs/features/models/index.md
docs/features/utility/application.md

The main objective was to add a link to the model inputs page in the features home page. There are also additional small fixes.

Misc doc fixes

---

outlines/backends/outlines_core.py

Our implementation of `outlines-core` was causing a bug in which the token generated that leading to a state that did not exist in the `FSM`. The origin of the problem is that the encoding of white spaces was different in the vocabulary and in the plain characters `DFA` built from the the regex such that no token in the vocabulary would exist for a white space.
The solution is to turn tokens into their string representations before building the Outlines Core `Vocabulary`.
I will additionally open a PR in `outlines-core` to:
- Add documentation on this behavior
- Raise an error when building an `Index` if the `Vocabulary` provided cannot create a complete FSM.

Turn tokens into strings before building the Outlines-Core Vocabulary

---

outlines/models/llamacpp.py

Closes #1709 
The origin of the problem lies in the setting of the `eos_token` and of the `vocabulary` in the tokenizer of `LlamaCpp` models for which the provided `Llama` instance does not have an HF tokenizer.
In this case, we have to use a workaround as the vocabulary is not directly accessible: we iterate over the token ids and decode them to have the associated tokens, ans similarly we get the `eos_token` by decoding the the `eos_token_id`. The issue is that the `eos_token` is a special token and the decoding modifies its string representation. To avoid this issue, we use the `detokenize` method with `special=True` for the `eos_token_id`.

Fix a bug regarding the eos_token in the LlamaCpp tokenizer

---

docs/features/models/vllm.md

This PR updates vLLM model references and API key usage in documentation.
The PR should close this issue: https://github.com/dottxt-ai/outlines/issues/1696

Update vLLM model references and API key usage in documentation

---

docs/features/models/llamacpp.md
docs/features/models/mlxlm.md
outlines/models/mlxlm.py
tests/models/test_mlxlm_type_adapter.py

Add support for the Chat input to the MLXLM model

---

outlines/models/llamacpp.py

Update the output_type formatting of the llamacpp model
