dottxt-ai/outlines

outlines/__init__.py
outlines/base.py
outlines/models/__init__.py
outlines/models/hf_diffusers.py
outlines/models/hf_transformers.py
outlines/models/openai.py
tests/models/test_hf_diffusers.py
tests/models/test_hf_transformers.py
tests/test_base.py

In this PR I introduce a `outlines.vectorize` function that works similarly to `numpy.vectorize`, and allows to turn functions into functions that take arrays as an input. The major differences with `numpy.vectorize` are:
1. The possibility to batch the execution. Launching too many concurrent calls at the same time, doing inference locally with a batch size too large may not be acceptable and thus we need to batch the parallel calls.
2. It will execute coroutines concurrently for better performance.
This function will be used internally for model calls, so we can pass arrays of arbitrary shapes as inputs and get an array of answers. Usual broadcasting rules apply:
```python
import outlines.models as models
complete = models.text_completion.openai("text-davinci-003")
prompts = …
```

Vectorize function calls

---

outlines/models/hf_transformers.py
tests/models/test_hf_transformers.py

The vectorization of `transformers` models is currently broken, mostly because when we batch prompts and add for several samples at the same time the model returns a flat array that we need to reshape. I added new tests.

Fix vectorization of `transformers` models

---

outlines/models/hf_transformers.py
outlines/text/masks.py
tests/text/test_masks.py

This PR adds a function that creates a mask from strings that represent a regex. I also add a aliases for a few frequent use cases:
- floats
- integers
- set of characters
Masks are returned as boolean `np.ndarray`, and can thus be combined using `|` (logical or) and `&` (logical and):
```python
>>> import numpy as np
>>> a = np.array([True, False, True])
>>> b = np.array([True, True, False])
>>> a & b
array([ True, False, False])
>>> a | b
array([True, True, True])
```
I originally used `torch.tensor`s but decided to use `numpy.ndarray`s in the end. While this could allow supporting models written with different frameworks, I am still wondering if the conversion to and from the frameworks would slow down the generation due to copying the content of the arrays.
In the Numpy-> Framework …

Create masks from regex

---

.github/workflows/tests.yml
pyproject.toml

Add coverage checks to CI

---

outlines/models/openai.py
pyproject.toml

Add retrying mechanism for openai api calls. 
Sample use cases
1. `complete = models.text_completion.openai("text-davinci-003", **{"wait_exponential_multiplier":1000, "wait_exponential_max":10000, "stop_max_attempt_number":5})`
2. `complete = models.text_completion.openai("text-davinci-003", **{"wait_random_min":1000, "wait_random_max":10000, "stop_max_attempt_number":5})`
Closes #115

Add retry mechanism for openai API calls

---

examples/parsing.py
outlines/text/parsing.py
pyproject.toml
tests/text/test_parsing.py

This PR introduces utilities for parser-driven masking: i.e. a parser is run alongside a language model's (LM) token sampling step and used to filter for grammar-valid next tokens.  `lark` was chosen as the underlying parser library because I have previous experience using it, its design is fairly straightforward, it's pure Python, and it supports arbitrary EBNF-like grammars.
The current approach is very experimental and is essentially driven by some patches to `lark`'s LALR parser.  Those patches allow for incremental additions to a lexed/parsed string, and, more importantly, they allow for partial token matches during scanning.  Partial tokens arise when the string being scanned cuts off without completely constructing/finalizing a token.  
For example, the source string `"def fo"` …

Add basic parser-driven masking utilities

---

outlines/text/parsing.py
tests/text/test_parsing.py

This PR picks up from #131 by extending/refactoring the partial parsing functionality so that it can be used more easily to pre-"parse" vocabularies in cases simpler than general context-free grammars (e.g. regex-only masking).
This is a subset of the functionality implied by https://github.com/normal-computing/outlines/issues/170.

Parser-driven masking updates for basic "off-line" vocabulary pre-parsing

---

outlines/models/hf_transformers.py
outlines/models/transformers.py
outlines/text/generate/continuation.py
outlines/text/generate/sequence.py
outlines/text/masks.py
pyproject.toml
tests/models/test_transformers.py
tests/text/generate/test_continuation.py
tests/text/generate/test_integration_transfomers.py
tests/text/generate/test_sequence.py
tests/text/test_masks.py

Use PyTorch instead of NumPy

---

outlines/models/tokenizer.py
outlines/models/transformers.py
outlines/text/generate/__init__.py
outlines/text/generate/continuation.py
outlines/text/generate/integer.py
outlines/text/generate/sequence.py
tests/text/generate/test_integer.py
tests/text/generate/test_integration_transfomers.py
tests/text/generate/test_sequence.py

In this PR I introduce a sequence generator that only outputs integers. Closes #153.
The generator can currently generate sequences that have leading zeros, which are then trimmed during post-processing. I am not sure what we should do about it. On one hand we can ignore it (maybe the LLM has seen this during training), on the other hand we could use the pre-processing approach described in #131.

Add `Integer` sequence generator

---

docs/source/overview.rst

Very nice work! Thanks!
Just started playing with it and got an error with the Hello World example in the documentation. This small modification fixed the issue for me.
Another remark: experimenting in a Jupyter notebook does not work  because of a pb with asynchio, see https://pypi.org/project/nest-asyncio/
The solution proposed there worked for me:
```
import nest_asyncio
nest_asyncio.apply()
```
It would probably be nice to refer to it in the documentation.
I hope this helps.
Best,
Marc

Fix overview document and a type hint

---

outlines/text/generate/continuation.py
outlines/text/generate/regex.py
outlines/text/generate/sequence.py
tests/text/generate/test_continuation.py
tests/text/generate/test_integration_transfomers.py

Stop generation with `Continuation` when a specific string was generated

---

examples/parsing.py
outlines/text/parsing.py
tests/text/test_parsing.py

This PR makes some simple generalizations to our custom `lark` parse state cloning.  It also adds SQL-guided generation as an extension to the existing LLM example.
N.B. Don't expect the example model (i.e. [`codegen-350M-mono`](https://huggingface.co/Salesforce/codegen-350M-mono)) to actually produce meaningful/interesting SQL; it was trained primarily/exclusively on Python code.  Also, the example SQL grammar could have issues of its own.

Generalize parse state cloning

---

outlines/models/tokenizer.py
outlines/models/transformers.py
outlines/text/generate/regex.py
tests/text/generate/test_regex.py

BPE tokenizers encode whitespaces as a special character `Ġ`, and it is possible that another tokenizer may encode one or several strings as special character(s). Partial matching with the tokens directly thus prevents relevant matches from happening. 
We thus add a `convert_token_to_string` method that converts back these special character to the string they correspond to so we can partially match the corresponding tokens with the regex.
The following snippet illustrates the problem and its solution:
```python
import interegular
from outlines.text.parsing import find_partial_matches
from outlines.models.transformers import transformers
model = transformers("gpt2")
fsm = interegular.parse_pattern("This is a new day").to_fsm()
pmatch = find_partial_matches(fsm, "Ġday")
print(pmatch)
pmatch …
```

Convert tokens to strings before partial matching

---

outlines/text/generate/__init__.py
outlines/text/generate/regex.py
outlines/text/parsing.py
tests/text/generate/test_integration_transfomers.py
tests/text/generate/test_regex.py
tests/text/test_parsing.py

Closes #152. I use the `Regex` generation method using a `(choice_1|choice_2|...|choice_n)` regex. This method is equivalent to rejection sampling: draw a token and discard it if it is not on a path that generates either of the choices.
An alternative implementation would be to tokenize the choices, do a forward pass through the model with each and sample from the resulting categorical distribution. However, some strings can be built from different combinations of tokens and we would only be considering one for each stopping sequence.
Unsurprisingly, the check to verify that a sequence can be generated with the vocabulary added in #175 fails. We fix this by checking whether we can build terminal paths with the vocabulary. Closes #184.

Generate a choice between different strings

---

.github/workflows/build_documentation.yml
.github/workflows/publish_documentation.yml
.github/workflows/release.yml
.github/workflows/tests.yml
README.md
environment.yml
outlines/text/generate/__init__.py
outlines/text/generate/regex.py
outlines/text/generate/sequence.py
outlines/text/json_schema.py
pyproject.toml
tests/text/generate/test_integration_transfomers.py
tests/text/generate/test_sequence.py
tests/text/test_json_schema.py

In this PR we add a new generation method that can generate valid JSON following a [Pydantic mode](https://docs.pydantic.dev/latest/#pydantic-examples) or [JSON Schema](https://json-schema.org/) specification.
We first parse the (possibly nested) JSON schema into a generation schedule, which is a list of strings that represent the JSON structure, and annotations that correspond to the field specifications. The following annotations are currently supported, with a minimal set of functionalities:
- `string`
- `int`
- `float`
- `bool`
- `Union[type1, type2]`
- `enum`
- `List[type]`
- `List[Union[type1, type2]]`
- `Optional[type]`
- Nested schema
- `maxLength` for strings
- `minLength` for strings 
The tests demonstrate how to build a schedule from Pydantic models, using the models' …

Add `JSON` generation method

---

README.md
outlines/models/transformers.py
pyproject.toml

Made the `transformers` requirement more explicit, by stating it in the README and raising an informative exception when trying to instantiate a model when the library is not installed.Closes #222. 
I also updated `pyproject.toml` to match the required Python version. Closes #234, #219. 
I also fixed an example in the README that was unclear. Closes #218

Make `transformers` dependency explicit

---

README.md
docs/source/index.rst
docs/source/installation.rst
docs/source/overview.rst
docs/source/reference/multimodel.rst
outlines/models/__init__.py
outlines/models/hf_diffusers.py
outlines/models/hf_transformers.py
outlines/vectors/retrieval.py

Hey, some small things I saw here, feel free to cherry-pick/discuss.

Fix some typos and language

---

README.md
outlines/text/generate/continuation.py
outlines/text/generate/regex.py
outlines/text/generate/sequence.py

Please correct me if I'm wrong about any of the below! But I noticed a few more things that seem mismatched in comments.

Fix some typos/language in `regex` and `sequence`

---

outlines/models/transformers.py
pyproject.toml
tests/models/test_transformers.py
tests/text/generate/test_integration_transfomers.py

Currently, there are some issues when loading a transformers model because it explicitly calls `.to(device)`. The default is "cpu" (which is already the default in transformers to begin with). So I recommend to remove `device` as an argument completely and let the user decide how they want to load the model. That allows things like device_map and loading in `kbit`. Internally inside the `Transformers` class nothing changes, but we set `self.device` to `model.device` to ensure that everything stays compatible in the rest of the library.
closes #238

Allow users to choose devices for models

---

outlines/text/json_schema.py
tests/text/test_json_schema.py

Escape curly braces in the regexes

---

README.md
outlines/text/generate/regex.py
outlines/text/generate/sequence.py

Change default generate behavior from fixed seed to random seed

---

examples/parsing.py
outlines/text/generate/regex.py
outlines/text/parsing.py
pyproject.toml
tests/text/partial_python.lark
tests/text/test_parsing.py

This PR is the first step to closing #170 using the approach described in our paper ["Efficient Guided Generation for Large Language Models"](https://arxiv.org/abs/2307.09702).
In other words, the changes in this PR allow us to create "index" `dict`s for full grammars.  By "index" we mean a `dict` that maps partial parse states to subsets of a vocabulary that are valid continuations of the parse state.
NOTE: The indexing work is being split off into its own PR.
TODO:
This will remove a large number of unnecessary states and decrease the overall cost of constructing indices.
They are currently being _completely_ ignored, which incorrectly excludes vocabulary strings consisting of only ignored tokens (e.g. `" "` in a Python grammar).

Use FSMs for scanning during grammar-guided generation

---

outlines/text/generate/regex.py
tests/text/generate/test_integration_transfomers.py

Findings with pythia-70m-deduped
Vocab size is 50304 (mentioned in original config) in https://huggingface.co/EleutherAI/pythia-70m-deduped/blob/main/config.json
Vocab size is 50254 (when we run - tokenizer.vocab_size from AutoTokenizer)
Vocab size is 50277 (when we run - len(tokenizer.get_vocab()) from AutoTokenizer)
Logit size is 50304 (when we call self.model(...) )
Now for GPT2 Vocab size and Logit size both are same 50257
This fix would create mask with size of Logit rather than vocab

Added a fix for missed match tensor size #213

---

outlines/models/transformers.py
tests/models/test_transformers.py

Fix missing spaces in `Tokenizer.convert_token_to_string`

---

outlines/text/json_schema.py
pyproject.toml
tests/text/generate/test_integration_transfomers.py
tests/text/test_json_schema.py

This PR allows whitespace characters according to the JSON grammar and disallows control characters in strings.
It also cleans up the project dependencies and pins `beartype` to a version below 0.16.0, because that version appears to be out of sync with its dependent package `pytorch`.

Fix whitespace and control character handling in JSON guidance

---

outlines/models/transformers.py
tests/models/test_transformers.py

Use `device_map` value when `device` is unspecified

---

docs/source/reference/batching.rst
docs/source/reference/controlled_generation.rst

Corrected some typos in the documentation which were causing the example code to fail.

Fix typos in model usage examples

---

outlines/text/json_schema.py
tests/text/test_json_schema.py

Previously, only `$ref` that were directed to `#/$defs` could be resolved via the use of a pre-loaded `definitions` variable. This PR modifies the behaviour of `$ref` resolutions by instead using a `resolver` function, which is generated to scope to a particular schema or subschema.
- This is still preloaded with `#/$defs` as before
- `$ref` keys are split to traverse through the scoped schema. When found, they are cached for re-use to avoid re-traversing
- In `expand_json_schema`, `$id` is an identifier of a scope change, and a new resolver linked to the schema for that scope is used for its children (e.g. for supporting [bundling](https://json-schema.org/understanding-json-schema/structuring#bundling))
- [Recursion](https://json-schema.org/understanding-json-schema/structuring#recursion) …

Modify JSON schema $ref resolution strategy to support resolving values internal to the schema

---

outlines/text/json_schema.py
tests/text/test_json_schema.py

In `expand_json_schema` -- used to denormalise the JSON schema -- only access and set the `title` property if present to avoid errors for schemas that have not set this optional property.
Fixes https://github.com/outlines-dev/outlines/issues/309

Fix JSON schema generation to accept schemas without 'title' property

---

tests/text/generate/test_integration_transfomers.py

This should fix the new issues arising from the newer version of `transformers`.

Update resize padding multiple in `test_transformers_logits_vocab_size`

---

outlines/models/transformers.py
tests/models/test_transformers.py

This PR changes the way that `transformer`'s special tokens are used in order to account for unhashable `special_tokens_map` values.

Avoid unhashable `additional_special_tokens` values in `special_tokens_map`

---

outlines/models/transformers.py
outlines/text/generate/continuation.py
outlines/text/generate/regex.py
outlines/text/generate/sequence.py
tests/models/test_transformers.py
tests/text/generate/test_integration_transfomers.py
tests/text/generate/test_sequence.py

This PR removes some unnecessary array allocations during the generation process that affect scaling in max tokens and adds KV caching.
Perhaps the biggest non-cache-based change is that the method `Sequence.update_token_ids` has been removed; otherwise, the dimensions for arrays returned by `Sequence.step` are fixed (i.e. no squeezing).  This makes the dimensions in `Sequence.__call__` clearer and allows us to simplify the loop (e.g. no need to duplicate the steps in the auto-regression loop before starting the loop).

Remove unnecessary array allocations in generation process and enable caching

---

outlines/text/generate/continuation.py
outlines/text/generate/regex.py
outlines/text/generate/sample.py
outlines/text/generate/sequence.py
tests/text/generate/test_continuation.py
tests/text/generate/test_sequence.py

This PR allows one to specify sampler functions that decide exactly how generated token sequences are sampled/produced from the logit values.  In doing so, this PR also adds a greedy "sampler" function (i.e. one that chooses the max logit values).

Allow configurable sampling steps

---

outlines/text/generate/regex.py
outlines/text/generate/sequence.py
tests/text/generate/test_integration_transfomers.py

This PR fixes an issue with setting the new `sampler` argument to `Sequence`, and the `stop` argument to `Regex`.

Fix some `Sequence` interface issues

---

outlines/text/json_schema.py
tests/text/test_json_schema.py

I have noticed that the origin outlines doesn't support recursive array type. To be clear, here is a example：
```python
from outlines.text.json_schema import build_regex_from_schema
from pydantic import BaseModel
from typing import List
import json 
class ItemModel(BaseModel):
name:str
class ArrayModel(BaseModel):
items:List[List[ItemModel]]
test_json = \
{
"items": [[{"name":"item1"},{"name":"item2"}]], 
}
json_schema = ArrayModel.model_json_schema()
print(json.dumps(json_schema,indent=2))
regex = build_regex_from_schema(json.dumps(json_schema))
print(regex)
parsed = ArrayModel.model_validate_json(json.dumps(test_json))
print(parsed)
```
Run the code above, then we can get the json schema of  `ArrayModel` , but we will get a error from `build_regex_from_schema` when we meet the …

Support recursive arrays in JSON when an item is an array

---

outlines/text/fsm.py
outlines/text/parsing.py
tests/text/test_fsm.py

This PR fixes a bug in `walk_fsm`, simplifies it, and provides a Python-only version for use with the parser (because it's faster due to less Numba dispatching overhead).

Fix and simplify `walk_fsm`

---

outlines/text/generate/sequence.py

This PR transfers all is-sequence-finished indices to the relevant devices during token generation.

Make sure that indices are available on all relevant devices

---

examples/babyagi.py
examples/meta_prompting.py

Fixes example scripts.
- Adds calls to *_fmt functions in `babyagi.py`, s.t. the script can work properly without triggering an Exception.
- Removes one stop criterion and increases max_tokens in a few calls, s.t. the answers by the GPTs are not truncated.

fixes BUG #353. Example scripts don't run as expected.

---

README.md

This pull request addresses an inconsistency found in the `Joke` class example within the README file of the `outlines` repository. The changes ensure that the inline documentation correctly reflects the actual output format.
- Updated the `Joke` class definition to use `Field` descriptors for `joke` and `explanation` attributes.
The previous version of the README included an example where the `Joke` class did not use `Field` descriptors, leading to a discrepancy between the class definition and the output format described in the comments. This could potentially cause confusion for users trying to understand the expected behavior of the `joke_ppt` function.
By introducing `Field` descriptors in the `Joke` class, the documentation now accurately reflects the structure and output format of …

Fix Documentation Inconsistency in Joke Class Example

---

outlines/models/openai.py

This PR allows users to supply an optional Openai API key, this is useful for services that allow users to supply their own API keys (like web services).

Add optional `api_key` parameter

---

docs/reference/json.md
examples/dating_profile.py
outlines/text/generate/regex.py
outlines/text/json_schema.py
tests/text/generate/test_integration_transfomers.py
tests/text/test_fsm.py
tests/text/test_json_schema.py

A common use case for JSON-guided generation is to extract values that are then passed to a function (see autonomous agents applications. This PR adds the possibility to extract the JSON specification from the signature of  a function. Under the hood we create a Pydantic model from the extract argument names and type annotation. 
The use interface is the following:
```python
from outlines import models
from outlines.text import generate
def do_something_with_result(foo: str, bar: List[int]):
pass
model = models.transformers("mistalai/Mistral-7b")
generator = generate.json(model, do_something_with_result)
args = generator("Generate arguments for the function")
do_something_with_result(**args)
```
Closes #350. Closes #351

Build a JSON schema from a function's signature

---

README.md
outlines/text/generate/__init__.py
outlines/text/generate/regex.py
outlines/text/types.py
tests/text/generate/test_integration_transfomers.py
tests/text/generate/test_regex.py
tests/text/test_types.py

`text.generate.format` takes a model, a Python type and returns a generator which, given a prompt, will output text in the format described by the Python type:
```python
from datetime import datetime
from outlines import models
from outlines import text
model = models.transformers("gpt2")
result = text.generate.format(model, datetime.date)("Which day is today?")
```
Closes #346.

Implement `text.generate.format` constrained generation

---

outlines/models/transformers.py

The `Release` action is currently failing because `transformers` and `datasets` are optional dependencies but imported at the top level in the module. I moved the imports to where they are needed.

Remove top-level imports of `transformers` and `datasets`

---

outlines/models/openai.py
pyproject.toml
tests/text/generate/test_sequence.py

This PR aims at solving this issue: https://github.com/outlines-dev/outlines/issues/361
The new Python sdk of Openai allows us to instantiate a client that we can then use for API calls. I thought it would make sense to put the instantiation of the client (and the import of the openai library) in the `__init__` of the `OpenAIAPI` class. 
An issue I ran into was that the functions `call_chat_completion_api` and `call_completion_api` would then receive the client as an argument which would cause problems with the `cache` decorator. I'm not sure what's the best way to handle that. I created two intermediary functions `cached_call_completion_api` and `cached_call_chat_completion_api` in the `__init__` of the `OpenAIAPI` class as it looked like the solution that required the fewest …

Modify the openai model to conform to the new openai sdk v1.0.0

---

outlines/models/openai.py

Removes unused arguments in `generate_base` and `generate_choice` openai model functions.
- self.client was not necessary, as the function already uses a callable pointing to a method of the self.client instance.
- max_tokens is not used in `generate_choice`.
- reduces samples to 1 when calling the openai API in `generate_choice`, as discussed in #368 . This fix is not too relevant, as the extra token-cost generated per call was just `samples-1`, but it corrects the code. Note that the alternative solution suggested is not feasible: One can call the api in parallel, but only with a same prompt. As the different samples diverge, both prompts and masks do so, hence any parallelization should be upstream from the API call.

Remove unused arguments from openai generate functions.

---

outlines/models/openai.py

Addresses #368.
It is quite verbose: adds two helper functions: `longest_common_prefix` and `get_choices_with_longest_common_prefix`.
Maybe you would order the code differently.
ITo make the solution 100% secure, instead of computing the "prefixes" string-based, it should be done "token-based". That would change just those two functions. Let me know what you think.
The algorithm follows the pseudo-code in the issue.

"Optimistic" is_in generation for openai.

---

.gitignore
examples/meta_prompting.py

there appears to be, at least in ChatGPT-3.5 a meta-cognitive 'think step-by-step' approach in every response.
I couldn't get def split_into_steps to output the correct answer with anything but the prompt in its current form.

step by step prompting and colons in prompts

---

outlines/models/gptq.py

it was a bit confusing to use `auto_gptq` while the library installation from pypi refers to `auto-gptq` 
https://github.com/PanQiWei/AutoGPTQ
The change should be helpful if the `ImportError` is raised

Correct `auto-gpt` name in exception

---

docs/reference/openai_text_generation.md
outlines/models/openai.py
pyproject.toml

A few improvements to the openai client.
- Added a function to wrap the call to async generate_chat, s.t. it can process the usage data and add an additional parameter (the system prompt).
- Added the system_prompt parameter: not groundbreaking, but just required a small change. It may reduce the need to do prompt composition. There was issue about this was closed as not planned. #246
- Added a timeout parameter: Without it sometimes the script was waiting for minutes and minutes for a 1-token response.
- Added the processing of usage: Accumulated usage is stored within each instance of the client. #387

Track usage, add system prompt and timeout

---

outlines/__init__.py
outlines/function.py
pyproject.toml
tests/test_function.py

In this PR we allow users to define end-to-end functions from a prompt template, a Pydantic model and a model name (that can be downloaded from the Hugging Face hub):
```python
import outlines
@outlines.prompt
def test_template(text: str):
"""{{ text }}"""
class Foo(BaseModel):
id: int
fn = outlines.Function(test_template, Foo, "gpt2")
```
These functions can then be executed, and imported by another module:
```python
from .foo import function as foo_fn
result = foo_fn("A prompt")
```
I also added a `from_github` classmethod that allows to directly download a function from a github repository:
```python
import outlines
fn = outlines.Function.from_github("outlines-dev/outlines/chain_of_density")
```
which looks for a variable named `fn` in the `chain_of_density.py` file in the …

Define end-to-end applications

---

outlines/models/openai.py

The client currently returns a `TimeOutError` after many requests. This seems to be a problem on the OpenAI side, but we provide this temporary fix so the OpenAI integration works fine in Outlines. Fixes #428

Create a new `AsyncOpenai` client for each request

---

outlines/generate/api.py
tests/generate/test_generator.py

Fix prompt removal logic and update test case

---

examples/vllm_integration.py

I patched `vllm.models_executor.layers.Sampler` to be able to pass the sequence id to the logits processor. FSM states are held in a `defaultdict` so we don't need to know the number of sequences in advance.

Update the vLLM example to work with batch requests

---

README.md

Updating Readme to point to the correct function `outlines.generate.text` instead of broken function calls.

Update README to point to latest function of LLM text

---

outlines/models/__init__.py
outlines/models/exllamav2.py
pyproject.toml

library: https://github.com/turboderp/exllamav2
To install exllamav2, you have to install the correct python & cuda version from the releases.
With proper caching, it's 3~4x faster than gptq.

Add integration for ExllamaV2

---

outlines/models/openai.py
tests/models/test_openai.py

This PR introduces a validation check for the `model_name` parameter within the `openai` method of the `outlines.models` module. The aim is to ensure that only valid model names are used when calling this function. As per the current implementation, any string passed as the `model_name` would be accepted.
The change enforces the function to only accept `gpt-4` or `gpt-3.5-turbo` as valid model names. If any other model name is passed, a ValueError is raised, informing the user about the invalid input and suggesting the correct model names.
This change also adds tests to `tests/models/test_openai.py`. To ensure an invalid model raises a value error. 
Note: I added `gpt-4-1106-preview` in the tests, so when or if it's added to the suite of models supported by outlines, that will need to be …

Add validation for model_name parameter

---

README.md
examples/cfg.py
outlines/fsm/fsm.py
outlines/generate/api.py
outlines/text/generate/api.py
tests/generate/test_integration_transfomers.py

This PR aims at solving [#417](https://github.com/outlines-dev/outlines/issues/417)
The proposed change does 2 main things:
- break the generation loop in `SequenceGenerator.__call__` if all sequences contain at least one of the stop_sequences provided by the user
- format the generated sequences to truncate them once the first stop_sequence is found in them
A downside of adding this logic at the level of the `SequenceGenerator` is that we generate text that is later discarded. However, incorporating this logic in the fsm would require much bigger change as we need to decode the token_ids to check whether the stop_sequences are found. Maybe this could be a first solution before some future refactoring.
As suggested in [#433](https://github.com/outlines-dev/outlines/issues/433), I think we …

Restore the ability to stop when a specified string has been generated

---

outlines/models/exllamav2.py

The Exllama2 integration currently imports `transformers` at the top level, when it's only needed for type checking. This will raise exceptions for anyone using the library with no intention to use `transformers` models.

Do not import `transformers` at top level in Exllama2 integration

---

examples/cfg.py
outlines/fsm/fsm.py
outlines/generate/api.py
outlines/generate/generator.py
tests/fsm/test_fsm.py
tests/generate/test_generator.py

This is an updated version of https://github.com/outlines-dev/outlines/pull/449/ up-to-date with `main` and with `examples/cfg.py` updated to remove the branch that checks the FSM `num_tokens_generated` attribute, which has now been removed.

Remove idx arg from FSM interface

---

.gitignore
docs/cookbook/index.md
docs/reference/models/llamacpp.md
docs/reference/models/openai.md
docs/reference/vllm.md
examples/llamacpp_example.py
mkdocs.yml
outlines/__init__.py
outlines/models/__init__.py
outlines/models/llamacpp.py
pyproject.toml
tests/models/test_llama_cpp.py

fixes #422 
This is a draft PR for a LlamaCpp integration using the low-level API.

Add LlamaCpp integration

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py
tests/generate/test_integration_transfomers.py

The aim of this PR is to solve issue #419

Support required keyword in JSON Schema

---

docs/cookbook/models_playing_chess.md

Hello, 
This was a fun example in the cookbook, but there were some elements missing, e.g., `model` was referenced in the code, but not defined anywhere, `board_state` was set to be the model, etc. 
I updated the example to use the smaller Phi-2 (which actually plays terrible, but otherwise longer chess) and added the code needed so [that the example can run.](https://colab.research.google.com/drive/1-f9CC64HGgaZhxZTvJkZPfenySkb0Yt7?usp=sharing)

Updates chess cookbook example with Phi-2 and adds omitted code. 

---

outlines/base.py

The logic to call `nest_asyncio` was added in https://github.com/outlines-dev/outlines/commit/587f9ac139651ff2e4af860fbd6e155f38eca675 presumably to make notebook interactions easier.
However, it's a bad practice to unconditionally call global python patches from library code.
It caused some issues with vLLM integration and was patched in https://github.com/outlines-dev/outlines/pull/481
We ran into different issues when using Outlines in our codebase. The unittests started hanging on shutdown because of stray asyncio threads.
I propose to make the patch happen only when running inside IPython. According to https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook it's an ok detention method for notebooks. Other proposed methods are too …

Patch nest_asyncio in notebooks only

---

outlines/models/__init__.py
outlines/models/azure.py
outlines/models/openai.py

Adds a wrapper around the `OpenAI` class, creating an `AsyncAzureOpenAI` client instead of an `AsyncOpenAI` client.
Also required one change to `openai.py`: I put the tiktoken logic inside a computed `tokenizer()` property so that I could override this in the subclass. This is necessary because Azure OpenAI has a distinction between a `deployment` and a `model`, the former of which is used when making calls to the API, but the latter is what must be passed to tiktoken.
Usage:
```python
model = outlines.models.azure_openai(
model_name="gpt-4",
deployment_name="gpt4-1106",   # my custom deployment name
azure_endpoint="https://<myendpoint>.openai.azure.com/",
api_key="<mykey>"
)
model.generate_choice(
"What is the capital of the country where DaVinci is from?",
choices=["Milan", "Rome", …
```

Support Azure OpenAI

---

docs/reference/vllm.md
outlines/serve/serve.py
outlines/serve/vllm.py

Hi,
This pull request adds support for CFG in vllm serving.

Add CFG to vllm serving

---

outlines/models/custom_openai.py
outlines/models/openai_compatible.py

Adds a new class to support for providing a custom base_url to the OpenAI client, and a couple of small updates to remove the checks on the model via the "retrieve" api (since it's not always available), sets tiktoken to use gpt4 by default (with the option to override it), and enables passing temperature as a named parameter to the __call__method to override the config.
Usage is basically the same as the regular OpenAI model wrapper, with the addition of the base_url parameter. Eg:
```
hermes = CustomOpenAI(
model_name="NousResearch/Nous-Hermes-2-Mixtral-8x7B-DPO",
system_prompt=system_prompt,
api_key="xxx",
base_url='https://api.together.xyz',
)
print(hermes(test_input))
```
The environment variables checked to set the API key was also updated, so as not to conflict with any OpenAI …

Added subclass of OpenAI class to support custom endpoints

---

pyproject.toml

Temporarily change to prevent failures described in https://github.com/outlines-dev/outlines/issues/568
Won't apply "fix" label because we don't know the root source of the issue (i.e. whether it's a result of incompatability or if it's a bad version of `transformers`)

Pin transformers version to 4.36.2

---

outlines/caching.py
pyproject.toml
tests/test_cache.py

Fixes https://github.com/outlines-dev/outlines/issues/561
Smoke test:
```
[nix-shell:~/p/outlines]$ git branch --show-current
clear-cache-upon-version-upgrade
[nix-shell:~/p/outlines]$ python3 -c "from outlines.fsm.fsm import RegexFSM; from outlines.models.transformers import TransformerTokenizer; RegexFSM('a', TransformerTokenizer('gpt2'))" && echo "success"
success
[nix-shell:~/p/outlines]$ git checkout benl/fsm-enhancements
[nix-shell:~/p/outlines]$ pip install . -q
[nix-shell:~/p/outlines]$ python3 -c "from outlines.fsm.fsm import RegexFSM; from outlines.models.transformers import TransformerTokenizer; RegexFSM('a', TransformerTokenizer('gpt2'))" && echo "success"
Traceback (most recent call last):
File "<string>", line 1, in <module>
File …
```

Clear cache upon version upgrade

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Add JSON schema field constraints addressing  #215 
So far this PR includes:
* date-time
* time
* date
* UUID

Implement JSON schema field constraints

---

outlines/generate/generator.py

Exllama generates logits in torch Half-dtype, but Outlines requires the Float-dtype. 
This small change converts the logits to the required dtype (whatever that might be), solving issue #583.
Tested with Exllama on the example code on the github front page, and #583 is resolved.

Bugfix:  Fixes dtype issue described in #583

---

docs/quickstart.md
outlines/__init__.py
outlines/fsm/fsm.py
outlines/grammars.py
outlines/grammars/arithmetic.lark
outlines/grammars/common.lark
outlines/grammars/json.lark
tests/test_grammars.py

Fixes https://github.com/outlines-dev/outlines/issues/543
Rendered docs: https://github.com/lapp0/outlines/blob/cfg-examples/docs/quickstart.md#built-in-grammars
Makes it easy to add grammars to the module, define a lark file in `outlines/lark`, reference it in `grammars.py`.
Work
Out of scope
- Fixing `escaped_string` per https://github.com/outlines-dev/outlines/issues/456
- Adding SQL, Python, etc grammars

Add grammars module

---

docs/reference/choices.md
docs/reference/index.md
docs/reference/types.md

Fixing an error
```
Traceback (most recent call last):
File "<string>", line 4, in <module>
File "/Users/gur/miniconda3/envs/jan25/lib/python3.10/site-packages/outlines/models/openai.py", line 128, in __init__
raise ValueError(
ValueError: Invalid model_name. Check openai models list at https://platform.openai.com/docs/models
```

Update index.md - fix model

---

tests/fsm/test_parsing.py

Fixes https://github.com/outlines-dev/outlines/issues/595
`test_grammars.py` fails if `test_parsing.py` is run first. This results in tests failing in https://github.com/outlines-dev/outlines/pull/539
This changeset ensures that `test_parsing.py` is isolated and doesn't impact other tests. 
Previously running the tests would impact `lark.lark.LarkOptions._defaults` (A class variable, not an instance variable), now the impact is erased via `importlib.reload(lark.lark)`

Reset `lark` package in `test_parsing.py`

---

outlines/fsm/json_schema.py
pyproject.toml

To harmonize with other regexes that are already in constants.
This will also allow to do monkey patching of this regex, to do experiments related to https://github.com/outlines-dev/outlines/issues/484

introduce WHITESPACE regex constant

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Makes the regex generated for json arrays more valid and flexible.
1. Allows for empty lists when min_items == 0
2. Allows whitespace between array elements
3. Adds support for maxItems (before, having any maxItems != minItems would allow infinite repeats)

Make json array generation more flexible

---

examples/self_consistency.py

```
{64: 1, 67: 9}
The answer is 67 with probability of 90.0%
```
* also reduces number of samples to 10 in order to avoid unexpected spendings when running this example

Update self_consistency.py - print actual answer

---

docs/reference/vllm.md
outlines/serve/vllm.py
pyproject.toml

Fixes https://github.com/outlines-dev/outlines/issues/576
Fixes https://github.com/outlines-dev/outlines/issues/504
vLLM `main` is incompatible with outlines. Do not merge until `vllm==0.2.8` is released, leaving as draft until then.

Bump vLLM version to `0.3.0`

---

docs/api/samplers.md
docs/reference/samplers.md
mkdocs.yml
outlines/generate/api.py
outlines/generate/cfg.py
outlines/generate/choice.py
outlines/generate/format.py
outlines/generate/generator.py
outlines/generate/json.py
outlines/generate/regex.py
outlines/generate/samplers.py
outlines/generate/text.py
outlines/samplers.py
outlines/text/generate/api.py
pyproject.toml
tests/generate/test_generator.py
tests/generate/test_integration_transfomers.py
tests/generate/test_samplers.py
tests/test_samplers.py

Closes #416 
- Do we make the sequence generator return arrays of shape `(num_samples * batch_size, num_tokens)`, and reshape in `SequenceGenerator`? Reshaping in the generator makes the latter much more complex. We could also not reshape at all, and let the user do it manually, which will simplify chained calls in the future.

Allow to generate several samples for each prompt

---

docs/reference/json.md
outlines/fsm/json_schema.py
outlines/generate/json.py
outlines/serve/vllm.py
tests/fsm/test_json_schema.py
tests/generate/test_integration_transfomers.py

Allow disabling `multiple_ws` argument in JSON constrained generation. Results in a maximum of one consecutive syntactic whitespace (no impact on string literals).
Fixes https://github.com/outlines-dev/outlines/issues/624

Allow JSON Schema Constraining to a Single Whitespace

---

outlines/fsm/types.py
outlines/generate/format.py
outlines/generate/json.py
outlines/generate/regex.py
tests/fsm/test_types.py
tests/generate/test_integration_transfomers.py

`generate.format` currently returns a string representation of the Python object that was passed to the function. In this PR we create and return the corresponding object from the generated string.
Closes #589

Make `generate.format` return the corresponding object

---

outlines/samplers.py

Fixes https://github.com/outlines-dev/outlines/issues/649

Ensure Ancestors on Correct Device During Sampling

---

outlines/serve/serve.py
outlines/serve/vllm.py

For `outlines/vllm` previously FSM-sequence correspondence was broken, resulting FSM state being mixed between sequences, corrupting output. To alleviate this, we have `_patched_apply_logits_processor` which passes a stable sequence ID to the logits processor.
In this PR we eliminate `_patched_apply_logits_processor` and cache FSM state based on the states input IDs.
Continuation of https://github.com/outlines-dev/outlines/pull/539 but much simpler because vllm upgrade fixed a lot of the issues being addressed there.
Related discussions:
- https://github.com/outlines-dev/outlines/issues/624
Fixes:
- Fixes #605 
- Fixes #610
Already fixed:
- https://github.com/outlines-dev/outlines/issues/524 (this one can be closed, as it's was addressed previously by upgrading vllm)
@viktor-ferenczi can …

Keep track of state in `RegexLogitsProcessor` using `input_ids`

---

outlines/generate/generator.py

Addressed the issue reported in #656 with the solution proposed by @rlouf . 
I am really not sure whether this is the best solution.

Put `ancestors` on the same device as the KV cache

---

README.md

Link to `grammars` module instead of deleted repo

---

.gitignore
docs/reference/models/llamacpp.md
examples/llamacpp_processor.py
outlines/fsm/fsm.py
outlines/fsm/json_schema.py
outlines/generate/api.py
outlines/generate/cfg.py
outlines/generate/choice.py
outlines/generate/json.py
outlines/generate/regex.py
outlines/generate/text.py
outlines/models/llamacpp.py
outlines/serve/vllm.py
pyproject.toml
tests/benchmark/test_benchmark_json_schema.py
tests/fsm/test_json_schema.py
tests/generate/test_integration_llamacpp.py
tests/models/test_llama_cpp.py

Note that this is super early.
We should probably provide a core implementation that all the other processors could inherit. Also the implementation of the tokenizer seems to be redundant.
Looking forward to some input.

Add llama logits processor

---

.github/workflows/release.yml
.github/workflows/release_docker.yml
.github/workflows/release_pypi.yaml
Dockerfile
README.md
docs/community/contribute.md
docs/quickstart.md
docs/reference/vllm.md

Fixes https://github.com/outlines-dev/outlines/issues/555
- Introduces dockerized `outlines.serve.serve`.
- Introduces automatic docker image push action to `release.yml`
- Example: [lapp0/outlines build](https://github.com/lapp0/outlines/actions/runs/7972431838/job/21764184361), [resulting image on Docker Hub](https://hub.docker.com/r/lapp0/outlines-serve)
Need some setup on your end please @rlouf:
- Let me know the outlines official docker repo URL so I can update `release.yml` and docs
- Configure the `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` secrets on GitHub in an environment named "release".
TODO: 
- Fixed, all steps (except publish PyPi) pass https://github.com/lapp0/outlines/actions/runs/7973090033/job/21766228377

Dockerize and Add Release-Push Workflow

---

.github/workflows/release_docker.yml
.github/workflows/release_pypi.yaml

Release Docker dispatch: https://github.com/lapp0/outlines/actions/runs/7994419887
- "Fails successfully": Got to the point where it only auth errors. `Error: buildx failed with: ERROR: denied: requested access to the resource is denied`
Not testing fetch PyPi. Changes are minimal between this version and the previous *working* main.
```
git diff e99d92d024dbf6f6bff10a9c3954f326cf4a0cd3 -- .github/workflows/release_pypi.yaml .github/workflows/release.yml | cat
diff --git a/.github/workflows/release.yml b/.github/workflows/release_pypi.yaml
similarity index 92%
rename from .github/workflows/release.yml
rename to .github/workflows/release_pypi.yaml
index e6bf1b1..597ebb7 100644
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release_pypi.yaml
@@ -1,16 +1,17 @@
-name: Release …
```

fix actions

---

docs/reference/custom_fsm_ops.md
docs/welcome.md
mkdocs.yml
outlines/fsm/fsm.py
outlines/generate/__init__.py
outlines/generate/fsm.py

This adds the outlines.generate.fsm() API entrypoint following https://github.com/outlines-dev/outlines/issues/670.

Add outlines.generate.fsm() API entrypoint

---

outlines/models/transformers.py
tests/generate/test_integration_transformers.py

This gives the option of specifying your own `PreTrainedTokenizer` instance rather than specifying a model name and having outlines construct the tokenizer for you. This might be convenient for situations where you are already using the LLM in other parts of your application and only need outlines for a specific use case.
Example of use:
```python
from transformers import AutoTokenizer, AutoModelForCausalLM
from outlines.models.transformers import TransformerTokenizer, Transformer
model_name = "hf-internal-testing/tiny-random-GPTJForCausalLM"
hf_tokenizer = AutoTokenizer.from_pretrained(model_name)
hf_model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = TransformerTokenizer(hf_tokenizer)
model = Transformer(hf_model, tokenizer)
```
As compared to before this change: …

Allow specifying own Hugging Face tokenizer instance

---

outlines/generate/api.py

Put `prompt_token_ids`, `attentions_mask` and `weights` on the same device

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fixes https://github.com/outlines-dev/outlines/issues/720

Fixing Enum with only one element being ignored

---

outlines/fsm/json_schema.py

I came across this bug while trying (and failing) to generate valid JSON based on a schema where property names contained parentheses. Since JSON property names can contain special characters, we should escape them while generating the schema's regular expression.

Escape JSON property names in regex

---

docs/reference/models/llamacpp.md
docs/reference/models/transformers.md
outlines/models/__init__.py
outlines/models/exllamav2.py
outlines/models/llamacpp.py
outlines/models/mamba.py
outlines/models/transformers.py
tests/benchmark/conftest.py
tests/fsm/test_regex.py
tests/generate/test_integration_transformers.py
tests/models/test_transformers.py

Clean the `transformers` and `llamacpp` interfaces

---

outlines/fsm/fsm.py
tests/fsm/test_fsm.py
tests/generate/test_integration_llamacpp.py

The final states of the FSM returned by `interegular` are not considered as final states since a recent change. This PR reverts this change.

Refactor the FSM module

---

outlines/integrations/utils.py

Some model use bytes as their tokens, such as Qwen (see: https://huggingface.co/Qwen/Qwen-7B/blob/ef3c5c9c57b252f3149c1408daf4d649ec8b6c85/tokenization_qwen.py#L136 )

Check if the given token is a string

---

outlines/fsm/regex.py

fixed parsing token vocabularies for gemma and gpt-sw3 models

---

outlines/integrations/vllm.py

fix: Do not reset `RegexLogitsProcessor._fsm_state`

---

docs/cookbook/classification.md

I noticed an import path must have changed and not been reflected in the cookbook examples for 'Classification' in the docs. I didn't see other examples. This PR only is for the example I noticed.

Small typo fix in cookbook example

---

docs/reference/json.md

Update the json function calling tutorial example that still use deprecated text module.

Fix missing text module from json documentation

---

outlines/models/openai.py

Switched order of AzureAsyncOpenAI to AsyncAzureOpenAI
to match name in repo 
https://github.com/openai/openai-python/blob/main/src/openai/lib/azure.py

Switched order of AzureAsyncOpenAI to AsyncAzureOpenAI

---

docs/reference/cfg.md

We add a small grammar guide based on the LOGO-like toy language example in the Lark repository.

Add a small grammar guide

---

docs/reference/models/transformers.md
outlines/generate/api.py
outlines/generate/generator.py
outlines/models/transformers.py
outlines/samplers.py
pyproject.toml

The `torch` and `transformers` libraries are installed by default with Outlines. These two dependencies are heavy, and not needed for the users who want to use the `llama-cpp-python` or `vllm`  integration. We thus make them optional.

Make `torch` and `transformers` imports optional

---

docs/cookbook/deploy-using-modal.md
examples/modal_example.py
mkdocs.yml

Based on the [example notebook](https://github.com/modal-labs/modal-examples/blob/main/06_gpu_and_ml/llm-structured/outlines_generate.py) in Modal's example repository. I also added a script that can be run directly in the `/examples` folder.

Add cookbook to run Outlines on the cloud with Modal

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Closes #759.
Here we forbid the generation of an odd number of escape characters, which would lead to an invallid JSON string.

Exclude escape character in JSON string fields

---

outlines/models/__init__.py

Currently, importing azure_openai as documented in https://outlines-dev.github.io/outlines/reference/models/openai/ does not work. Importing azure_openai as documented results in "AttributeError: module 'outlines.models' has no attribute 'azure_openai'"
Adding azure_openai to __init__.py fixes that behaviour. Currently, only way to import azure_openai is with `from outlines.models.openai import azure_openai`

Add azure_openai to models __init__.py

---

docs/cookbook/deploy-using-bentoml.md
examples/bentoml/.bentoignore
examples/bentoml/bentofile.yaml
examples/bentoml/import_model.py
examples/bentoml/requirements.txt
examples/bentoml/service.py
mkdocs.yml

Similar to #803, I made an example of running outlines with BentoML locally or in the cloud. Any feedback is welcomed. Thanks!

Add cookbook to run Outlines on the cloud with BentoML

---

outlines/fsm/fsm.py
outlines/fsm/guide.py
outlines/generate/generator.py
outlines/integrations/transformers.py
tests/fsm/test_fsm.py
tests/fsm/test_guide.py

This change removes the need to copy the entire list of token IDs during basic generation.  (N.B. I'm not a fan of the use of `None` to indicate the full vocabulary, but it's simple and does the job.)
More can be done to improve this situation dramatically (e.g. return the original logits untouched, update the original logits array in-place using the disallowed token IDs in other cases, etc.), but a change like this is a good start.

Remove the need to copy all tokens during basic generation

---

docs/reference/types.md
outlines/fsm/types.py
outlines/types/__init__.py
outlines/types/airports.py
outlines/types/countries.py
outlines/types/isbn.py
pyproject.toml
tests/test_types.py

This PR adds extra custom types:
- ISBN
- Valid airport IATA codes (enum)
- Valid country alpha-2 codes (enum)
- Valid country alpha-3 codes (enum)
- Valid country numeric codes (enum)
- Valid country names (enum)
- Valid country flags (enum)

Add more custom types

---

pyproject.toml

`pytest` seems to be pretty strict with these warnings.
This PR ignores errors caused by import warnings from `huggingface_hub` & `pyairports`

Ignore errors caused by import warnings from `huggingface_hub` & `pyairports`

---

outlines/generate/generator.py

Fixes https://github.com/outlines-dev/outlines/issues/685 which was most likely introduced by the `CFGGuide.copy()` operation added in https://github.com/outlines-dev/outlines/pull/618
This is just a hotfix & probably doesn't work when doing beam search

Hotfix for CFG Generation

---

docs/reference/types.md
outlines/types/__init__.py
outlines/types/locales.py
outlines/types/phone_numbers.py
outlines/types/zip_codes.py
tests/test_types.py

Some types such as zip code, phone number, etc. are locale-dependent. In this PR we introduce a mechanism that allows users to specify the locale:
```python
from outlines import types
types.locale("us").ZipCode
types.locale("us").PhoneNumber
```

Localize types

---

outlines/fsm/json_schema.py

Currently, `get_schema_from_signature` creates a json where `"title": "Arguments"`. This PR changes this so that the `"title"` will instead be mapped to the function's name.
Here is an example. I have this code snippet:
```python
from outlines.fsm.json_schema import get_schema_from_signature
def test_add(a: int, b: int | None = None):
if b is None:
return a
return a + b
schema = get_schema_from_signature(test_add)
print(schema)
```
Before this PR, this outputted
```python
{'properties': {'a': {'title': 'A', 'type': 'integer'}, 'b': {'anyOf': [{'type': 'integer'}, {'type': 'null'}], 'title': 'B'}}, 'required': ['a', 'b'], 'title': 'Arguments', 'type': 'object'}
```
and after this PR, this outputted
```python
{'properties': {'a': {'title': 'A', 'type': 'integer'}, 'b': {'anyOf': [{'type': …
```

Extract function name in `get_schema_from_signature`

---

outlines/fsm/guide.py
tests/fsm/test_fsm.py
tests/fsm/test_guide.py

Fixes #856
The code this PR removes introduces an artificial and erroneous loop transition in every final state that is always traversed, regardless of the generation.
The comment doesn't make sense in my opinion, as the `if` above just handles exactly this case.
Removing this piece of code fixes the bug that surfaced in the upgrade of outlines in the vLLM integration.

Remove broken final state loop

---

outlines/generate/api.py

Fixes https://github.com/outlines-dev/outlines/issues/896

Fixing stream stopping at wrong location

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fixes #823
This comment details the issues error: https://github.com/outlines-dev/outlines/issues/823#issuecomment-2116490949
The reproduction code provided results in a json schema with `OneOf[pets]`:
```
class Model(BaseModel):
pet: Union[Cat, Dog] = Field(..., discriminator='pet_type')
```
Before this PR: `OneOf` uses negative lookaheads to assert that only one schema member is included. This is illegal in `interegular`, more details available here: https://github.com/outlines-dev/outlines/issues/456
After `OneOf` uses or-joined non-capturing groups which don't have the same issues with `interegular`.

Prevent Illegal Look-Around for OneOf in JSONSchema

---

outlines/integrations/llamacpp.py
outlines/models/llamacpp.py
tests/generate/test_integration_llamacpp.py

Fixes https://github.com/outlines-dev/outlines/issues/820
llama.cpp's pre-tokenizer doesn't handle unicode properly (draft PR: https://github.com/ggerganov/llama.cpp/pull/5613). This results in tokens which are incompatible with Outlines byte-wise FSM and causes #820's error.
- 1) If `models.llamacpp()` specifies a `LlamaHFTokenizer`, populate the vocabulary used in index construction with `tokenizer.get_vocab()`. This takes advantage of huggingface's working pre-tokenizer.
- 2) Warn users that they should pass a `LlamaHFTokenizer`:
```
>>> from outlines import models, generate
>>> model = models.llamacpp("Qwen/Qwen1.5-0.5B-Chat-GGUF", "*q8*.gguf")
/opt/conda/lib/python3.10/site-packages/outlines/models/llamacpp.py:294: UserWarning: llama.cpp pre-tokenizer is broken. You may recieve an …
```

Circumvent Broken llama.cpp Pre-Tokenizer

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fix #838
https://github.com/outlines-dev/outlines/commit/06d565496966f0dbe184dd619b62ea276035f562 erroneously disallowed parenthesis in strings. This PR allows parenthesis in strings.

Allow Parenthesis in `STRING_INNER`

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fixes #844
We cannot create a pattern using `build_regex_from_schema()` using `{"type": "object"}` unless `additionalProperties` is set. The JSON Schema spec allows `additionalProperties` to be unset. If it's unset, the object has no constraints.
If `additionalProperties` is unset, create pattern allowing for object with any value type by recursively passing `{"anyOf": [{"type": "number"}, ...]}` to `build_regex_from_schema()`.
To keep the pattern finite, we set the default object nesting depth to 2.

Allow Objects Which are Unconstrained (No `additionalProperties`) in JSON Schemas 

---

.pre-commit-config.yaml
outlines/fsm/regex.py
pyproject.toml

Fixes #810 
Use `tqdm` progress bar within `regex.py`'s `create_fsm_index_end_to_end()` so the program doesn't silently hang with no indication of status.
Update pre-commit hook to ensure `types-tqdm` is installed for `mypy` type checking.
```
$ python3 810.py 
Compiling FSM index for all state transitions: 62%|██████████████████           | 146/235 [00:12<00:00, 18.96it/s]
```
Contents of `810.py`:
```python
import interegular
from transformers import AutoTokenizer
from outlines.models.transformers import TransformerTokenizer
from outlines.fsm.regex import (
make_deterministic_fsm,
make_byte_level_better_fsm,
create_fsm_index_tokenizer
)
regex_str = "(?:(?:[0-9](?:(?:_)?[0-9])*(?:e|E)(?:(?:\\+|\\-))?[0-9](?:(?:_)?[0-9])*|(?:[0-9](?:(?:_)?[0-9])*\\.(?:[0-9](?:(?:_)?[0-9])*)?|\\.[0-9](?:(?: …
```

Use TQDM to track index compilation progress

---

outlines/caching.py
outlines/fsm/guide.py
outlines/models/transformers.py
pyproject.toml
tests/generate/test_integration_transformers.py
tests/models/test_transformers.py

This PR removes the use of hash values as the keys to the underlying function call cache.  It also adds the tokenizer to the arguments of `create_states_mapping`.
The main change here is that `hash_arguments` has been removed and replaced with a `Disk` subclass, `CloudpickleDisk`, that uses `cloudpickle`.  This allows all the same objects to be cacheable as before, while also removing the use of hash values as keys.  The latter is especially important, since hash collisions at the key level can return the wrong results from the cache.
Likewise, the `key_function` argument to `cache` has been removed.  If one needs this sort of functionality, they can wrap the corresponding arguments with objects that properly implement serialization.
Closes #872

Update caching and add tokenizer to `create_states_mapping`

---

docs/reference/json.md
outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fixes #839 #908 #690 #450
A major problem, especially with smaller language models, is the repetition problem. 
For example, let's say a model is generating json and must provide 12 space tokens for indentation in json output. Often a language model will assign a high probability to a 13th space token, and do the same for a 14th space, and then enter an infinite space generation loop.
This is a problem with NLG that has been known for half a decade, but only has mitigations (mirostat, repetition penalty, using hundreds of billions of weights, etc), no absolute solutions (except for **structured generation**)
For structured json generation, we set a sane default whitespace pattern of `r"[ ]?"`. This removes all newlines and indentation. It disallows any syntactic whitespace beyond a single …

Use less problematic whitespace token

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fixes https://github.com/outlines-dev/outlines/issues/913
Enables complete version of PR https://github.com/outlines-dev/outlines/pull/914 which allows arrays
- Unconstrained arrays (arrays without any `items` types specified) would always result in an illegal regex
- Unconstrained arrays couldn't contain objects or arrays
- Fix Unconstrained array pattern so it doesn't produce an illegal pattern
- Allow objects and arrays within arrays, but use "mock" `depth` key to prevent infinite recursion

Fix invalid regex in unconstrained arrays for json_schema.py

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fix #749 
`{}` wasn't handled at all in `json_schema.py`, resulting in a `ValueError`.
Now it follows the json schema spec: allow **anything**: bool, int, object, etc, etc.

Allow json schema of `{}`, resulting in unconstrained json value

---

outlines/integrations/llamacpp.py
outlines/models/llamacpp.py
tests/generate/conftest.py
tests/generate/test_integration_llamacpp.py
tests/generate/test_integration_transformers.py

Fixes #922
`integrations/llamacpp.py` / `LlamaCppTokenizer` has `self.decode = model.tokenizer.decode`. This is not pickle-able. Attempting to pass a `LlamaCppTokenizer` to a `@cache`d function results in  `cloudpickle.dumps(tokenizer)` which causes `ValueError: ctypes objects containing pointers cannot be pickled` error.
Locally most `test_integration_llamacpp.py` fail.  (full test failure details in #922)
Make `LlamaCppTokenizer` subclass `outlines.models.tokenizer.Tokenizer` and implement its abstract methods. Specifically `__getstate__` is necessary to ensure `cloudpickle.dumps` works and hashing is possible.

Fix llamacpp caching by making `LlamaCppTokenizer` an outlines `Tokenizer`

---

.github/scripts/build_sdist_and_wheel.sh
.github/workflows/release_pypi.yaml
.github/workflows/tests.yml
pyproject.toml

Fixes #934
- Release to PyPi failed for v0.0.42 because `pycountry` and `pyairports` wasn't in `pyproject.toml` required dependencies
- We merged code which caused this failure without detecting it.
- Add `pycountry` and `pyairports` to `pyproject.toml` required dependencies
- Add Test SDist and Build Wheel to PR Test Suite
Example: failing workflow without `pycountry` and `pyairports`
- https://github.com/lapp0/outlines/actions/runs/9332636096/job/25688717515
Example: Release to PyPi using new workflow, works up to the point it 403s. I expect it to release provided a correct pypi token, but I can smoke test first if you prefer.
- https://github.com/lapp0/outlines/actions/runs/9333098031/job/25689734009

Fix Missing `pyproject.toml` Deps, Breaking `Release PyPi` Workflow & Add Build Wheel / SDist Check to PR Workflow

---

docs/community/versioning.md
docs/versioning.md
mkdocs.yml

We want to ensure downstream users are aware of Outlines versioning scheme and how to safely depend on and pin Outlines.
Create a documentation page
Rendered: https://github.com/lapp0/outlines/blob/versioning-docs/docs/versioning.md

Add Documentation on Outlines Versioning and Releases

---

outlines/fsm/parsing.py
outlines/fsm/regex.py
tests/fsm/test_parsing.py
tests/fsm/test_regex.py

Follow-up to https://github.com/outlines-dev/outlines/pull/904 by @M0gician  -- Closes #904
Fixes https://github.com/outlines-dev/outlines/issues/833
@m0gician identified [a bug in numba's handling of `UnicodeCharSeq`](https://github.com/numba/numba/issues/9542). if the elements first item is `\x00`, the entire element is null. This numba bug resulted in a `KeyError` while compiling a patterns index for certain characters.
More problem details available in #904
@m0gician implemented the base solution - represent token bytes with `numba.unicode_type` to avoid this bug.
https://github.com/outlines-dev/outlines/commit/4a5ef55d683f72f18f50e5f7e49ede742cee91fa
Use of `unicode_type` results in ambiguous representation of hex-bytes / chars.
E.g. in main a `UnicodeCharSeq` will keep the hex bytes …

Fix null byte `\x00` issue in byte level fsm resulting in `KeyError` in `BetterFSM::FSMInfo` 

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

This would allow to mitigate some repetition issues that certain LLMs have. This should resolve #847

Support min/max number of digits for numbers in JSON Schema

---

docs/cookbook/deploy-using-cerebrium.md
docs/stylesheets/extra.css
examples/cerebrium/cerebrium.toml
examples/cerebrium/main.py
mkdocs.yml

Supersedes (could not push to repository) #958

Add cerebrium as deployment option in documentation

---

docs/reference/models/mlxlm.md
docs/reference/models/openai.md
mkdocs.yml
outlines/models/openai.py

Closes #947.
We also update the `outlines.models.openai` and `outlines.models.azure_openai` functions so they accept every parameter that the clients provided by the `openai` SDK accept.

Update the documentation for OpenAI models

---

outlines/types/airports.py
outlines/types/countries.py
pyproject.toml

Since https://github.com/outlines-dev/outlines/pull/955 was closed with the reason that there was no interest in adding another step to the CI pipeline, it might still be worthwhile to resolve some issues with the project's dependencies without adding `deptry` to the project or the CI pipeline. This PR:
- Removes the obsolete try-except blocks for importing `pyairports` and `pycountry`, since they are listed in the project's dependencies.
- Add the transitive dependency `typing_extensions` to the dependencies
- Remove `ray` as a development dependency
Let me know your thoughts :) Feel free to close if you think it does not bring improvement to the project

Fix some dependency issues and remove obsolete try-except block

---

docs/cookbook/deploy-using-modal.md
examples/modal_example.py

[Modal renamed the Stub class to App](https://modal.com/docs/guide/apps#apps-were-once-stubs), updating the docs accordingly.

Update Modal refs from stub to app

---

pyproject.toml

Addresses: https://github.com/outlines-dev/outlines/issues/976
Fixes https://github.com/vllm-project/vllm/pull/5582
We should close 976 **after** we fix Outlines to be compatible with Numpy >= 2.0.0, which this PR doesn't do.
Cannot `import outlines` due to `outlines/base.py` importing `from numpy.lib.function_base import (` which no longer exists in numpy 2.0.0.
Pin `numpy<2.0.0`

Pin Numpy: `numpy<2.0.0`, Prevent `ModuleNotFoundError`

---

outlines/models/__init__.py

Very excited about the mlx integration in [v0.0.44](https://github.com/outlines-dev/outlines/releases/tag/0.0.44)! 
Began integrating it into a project, but noticed that type hinting was throwing some errors around the `LogitsGenerator` type. Essentially, it looks as though this type wasn't synced up with the creation of the two new models. 
This PR just adds the two models to this type in `models/__init__.py`: 
```python
LogitsGenerator = Union[Transformers, LlamaCpp, ExLlamaV2Model, Mamba, MLXLM, VLLM]
```
However, it brought up a bigger design question I'm curious about. What was the reasoning to go with this pattern (building a custom type using `Union`) as opposed to an abstract `LogitsGenerator` class, which all future model classes subclass? This way:
- You wouldn't need to worry …

Adding `MLXLM`, `VLLM` classes to `LogitsGenerator` type

---

docs/cookbook/classification.md
outlines/samplers.py

This fixes issue #978. Specifically for the classification example in the outlines cookbook section [here](https://outlines-dev.github.io/outlines/cookbook/classification/),  it fixes the piece of code in outlines.generate.api.SequenceGeneratorAdapter that keeps returning the wrong result (i.e. returning False even if a specific sampler is passed (greedy, multinomial, or beam search).

Fix samplers documentation

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Use JSON's serialization, rather than Python's, in this case.
Fixes #971. Note that this still does not correctly handle arrays and objects, which are allowed by the JSON schema spec; however, those would be more complex to handle correctly.

Ensure regex matches valid JSON for "const" and "enum" with booleans, nulls, and strings

---

docs/community/examples.md

This is still a draft doc of the method & I'm currently coordinating with the MMFM team to improve it further. Will mark this as 'ready' when the final report gets uploaded to their website.

Add link to docs of Multimodal Structured Generation for CVPR 2nd MMFM Challenge

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fixes https://github.com/outlines-dev/outlines/issues/935
On `main` in `json_schema.py`,
`STRING_INNER = r'([^"\\\x00-\x1f\x7f-\x9f]|\\\\)' `
This pattern requires `\` to be followed by a second `\`.
`\\` is legal, `\"` is not.
Modify the pattern so `\\` AND `\"` are allowed.

Allow escaped strings in `json_schema.py`

---

docs/reference/models/openai.md

Superses #990 since couldn't push to author's branch

Fix use of `os.environ` in documentation

---

outlines/fsm/json_schema.py
tests/fsm/test_json_schema.py

Fixes https://github.com/outlines-dev/outlines/issues/931
`interegular` doesn't support anchors, `^` and `$`, however `json_schema.py` explicitly allowed their inclusion in `main`, resulting in `interegular.patterns.Unsupported: '^'`.
- Strip anchors in pattern-strings.
- update `json_schema.py` tests so any produced regex is run through `interegular.parse_pattern(regex)` to check for `interegular` incompatibility.

fix pattern-string in `json_schema.py` by removing anchors

---

outlines/models/llamacpp.py
tests/generate/test_integration_llamacpp.py

Fixes https://github.com/outlines-dev/outlines/issues/952
During FSM index creation, the **normalized** vocabulary is used to determine token validity for each state in the automata. 
Because the set of token strings in `tokenizer.vocabulary` isn't equivalent to the token strings created by `tokenizer.decode` the vocabulary tokens must be normalized to ensure the FSM selects tokens from the vocabulary which, when decoded, conform to the pattern. 
In `models.llamacpp` there wasn't any normalization, and the `\n` token is represented in vocabulary as `Ċ`
```
>>> tokenizer.vocabulary['Ċ']
198
>>> tokenizer.decode([198])
['\n']
```
During FSM compilation, Outlines understood `"Ċ"` to be a valid json string, however in reality, the invalid json string `"\n"` was decoded.
Implement working …

Fix Incorrect Token Normalization Method for `LlamaCppTokenizer`

---

outlines/models/llamacpp.py
tests/generate/test_integration_llamacpp.py

Fixes #973 
In #973 an invalid pattern was being generated, however it was only invalid because it was incomplete. in the `LlamaCpp.generate()` call `llama_cpp_params["max_tokens"]` was unset, however the model was still finishing for reason "length":
```
[{'text': '{ "name": "Grace Lee", "age":32, "', 'index': 0, 'logprobs': None, 'finish_reason': 'length'}]                                                                                                         
```
In turns out the max tokens was being implicitly set to `30`.
Allow 2**30 tokens if `max_length` is unset /`None`, because `llama_cpp_params` requires an `int` for the `max_tokens` field.

Ensure `models.llamacpp` Doesn't Have Implicit `max_tokens`

---

outlines/models/mlxlm.py
tests/generate/conftest.py
tests/generate/test_generate.py

Fixes https://github.com/outlines-dev/outlines/issues/982
`models.mlxlm` didn't properly apply whitespace prefixes for some tokenizers such as `phi3`.
Use official `mlx-lm` implementations `tokenizer.detokenizer` to manage last-token str representation when iterating over token strings.

fix `models.mlxlm` whitespace prefix handling

---

outlines/models/vllm.py

Very minor change that adds the possibility to avoid displaying progress bars within `outlines`. It is not changing the default behaviour and is just about adding an argument (`use_tqdm`) to the `LLM.generate` call.
It was useful for a personal project and I did not find another way to do so, so I decided to PR this.

Adding the option to avoid displaying tqdm bars at inference with `vllm`

---

pyproject.toml

- Fixes Discord user Vibhath's issue with `mlx-lm` on linux.
- Fixes https://github.com/outlines-dev/outlines/issues/989
`pip install -e .[test]` fails under two addressed conditions:
- gnu/linux user attempts to install `mlx-lm` dependency
- darwin user attempts to install `vllm` dependency.
Update `pyproject.toml`, ensure `vllm` and `mlx-lm` are installed only on appropriate systems.

Update `pyproject.toml`, enable `mlx-lm` requirement only on darwin, disable `vllm` requirement on darwin

---

docs/community/examples.md

AskNews is processing 300k articles per day on-premise with vLLM and outlines. Outlines enables much deeper analysis of each article, since the LLM doesnt need to worry about structure. Instead, it can focus attention on important output like extracting "Reporting Voice" typed as a `Literal[str]`.
Thanks to the maintainers of this project!

Add asknews example

---

benchmarks/bench_processors.py
outlines/__init__.py
outlines/models/mlxlm.py
outlines/processors/__init__.py
outlines/processors/base_logits_processor.py
outlines/processors/structured.py
tests/generate/test_generate.py

A lot of these fixes were intended for https://github.com/outlines-dev/outlines/pull/966 however that's blocked until there's a new `transformers` release. 
These improvements are general to all models and will enable PRs resolving https://github.com/outlines-dev/outlines/issues/806 and https://github.com/outlines-dev/outlines/issues/965
The goal is to create a base class which allows a logits processors to be implemented once and used for any `outlines.models` inference library.
To accomplish this we must normalize the input array. It must have a consistent type (`torch.Tensor`) and consistent dimensionality (2). We can normalize both of these simply, and without any copy operations.
`mlx.core.array`, `numpy.array`, and `torch.Tensor` all support [pythons array standard …

Improve `outlines.processors`, add integration tests to test_generate.py

---

benchmarks/bench_processors.py
docs/community/contribute.md
outlines/fsm/guide.py
tests/fsm/test_fsm.py
tests/fsm/test_guide.py

Fixes https://github.com/outlines-dev/outlines/issues/1011
Fixes https://github.com/outlines-dev/outlines/issues/920
Runtime performance for structured generation was weak because the legal next token mask is `List[int]` in main. This is inefficient because we have to convert a list of potentially tens of thousands of integers to `torch.tensor`.
Cache legal next token ids as a `torch.tensor`. Don't construct the mask from `List[int]`, construct it from `torch.Tensor`.
With a vocabulary of ~50,000 tokens, worst case performance decreases 50-fold.
```
| Change   | Before [833f68f8]    | After [d9baa1ba]    |   Ratio | Benchmark (Parameter)                                                                            |
|----------|----------------------|---------------------|---------|---------- …
```

`RegexFSM`: Cache Legal-Token Mask as `torch.Tensor` to Improve Performance

---

outlines/generate/api.py

The following lines break in batched generation.
There is a single list that is 
`[b_0_s_0, b_0_s_1, b_0_s_2, b_0_s_3, b_1_s_0, b_1_s_1, ...]`
with `b_0_s_0` being the example generated for batch 0 and sample 0 of multi-sample batch generation.
At the end of the generation code, the following tries to separate the generated samples in a `batch_size` quantity of sub lists. The problematic code is as follows:
```python
for i in range(batch_size):
output.append(formatted[i : i + num_samples])
```
We indeed get a list of batch size, but not the expected ones. Instead it should be:
```python
for i in range(0, batch_size * num_samples, num_samples):
output.append(next_tokens[i : i + num_samples])
```
As an example, using the prompts: 
`'1 1 1 + 3 3 3 =? Solution: 1 1 1 + 3 3 3 =`  
and 
`'2 2 2 …

Major bug & fix: Fix bug in batched multi sample generation

---

docs/stylesheets/extra.css

Minor style change for file contributors for accessibility.
| BEFORE | AFTER |
|--------|--------|
| <img width="1512" alt="Frame 1235" src="https://github.com/user-attachments/assets/1e337348-3553-4a36-be8f-550102b76961"> | <img width="1512" alt="Frame 1234" src="https://github.com/user-attachments/assets/02d3dc79-cb58-4a62-baa8-94200d1b5818"> |
| <img width="397" alt="Frame 1236" src="https://github.com/user-attachments/assets/8775cec1-a5e9-4de0-99be-0f8638569e17"> | <img width="397" alt="Frame 1237" src="https://github.com/user-attachments/assets/750cd9c1-3d27-4c09-b979-d38d217bca88"> |

Update file contributors style for docs

---

outlines/fsm/guide.py
outlines/fsm/regex.py
outlines/models/llamacpp.py
outlines/models/tokenizer.py
tests/fsm/test_regex.py

As [discussed in our Discord server](https://discord.com/channels/1182316225284554793/1182317446225481788/1261998326077984802)
This PR adds support for custom regex parsers. This doesn't change the behavior of Outlines by default. But this allows us to write custom `Guide` classes that uses custom regex parsers for e.g. multimodal generation.
Also improves documentation

Adds support for custom regex parsers (for multimodal structured generation)

---

README.md
docs/reference/models/transformers.md
docs/reference/text.md
examples/llamacpp_example.py
outlines/generate/cfg.py
outlines/generate/regex.py
outlines/generate/text.py
outlines/models/__init__.py
outlines/models/transformers.py
tests/generate/test_integration_llamacpp.py
tests/generate/test_integration_transformers.py
tests/models/test_transformers.py

~~In draft until https://github.com/huggingface/transformers/pull/31448 makes it into a new `transformers` release~~
Fixes https://github.com/outlines-dev/outlines/issues/1021
Fixes #789
Fixes #806 (does everything except remove the issues requirement of "remove `torch`")
Closes https://github.com/outlines-dev/outlines/pull/910 (device inconsistency issue handled through other means)
- For #789 in `SequenceGenerator` if `input_ids` is empty, it fails.
- Generally, `models.transformers` has an inconsistent implementation with other modules making the codebase harder to manage.
- Use `SequenceGeneratorAdapter` for transformers instead of `SequenceGenerator`
- Implement `Transformers.generate` and `Transformers.stream` which use `model.generate(logits_processor=...)` argument with …

Update `models.transformers` to use `SequenceGeneratorAdapter` and `OutlinesLogitsProcessors`

---

outlines/fsm/guide.py
outlines/generate/fsm.py
outlines/generate/regex.py
outlines/generate/text.py
outlines/models/llamacpp.py
outlines/models/transformers.py
outlines/processors/base_logits_processor.py
tests/generate/test_generate.py

Fixes https://github.com/outlines-dev/outlines/issues/965
in `main`
- `generate.fsm` only supports `SequenceGenerator`, 
- `models.llamacpp` doesn't support `SequenceGenerator`, it only supports `SequenceGeneratorAdapter`
- `integrations.llamacpp` doesn't have a FSM logits processor.
- Ensure `models.llamacpp` uses `outlines.processors` / `SequenceGeneratorAdapter` for all generators
- Update `generate.fsm` to use `SequenceGeneratorAdapter` for all unified models
- `test_generate.py` tests for `generate.fsm` on `MLXLM`, `llamacpp`, and `transformers` (the three models using  `outlines.processors`)
- fix critical `generate.fsm` bug discovered through this test in `guide.py` impacting all models

Use `outlines.processors` for `models.llamacpp`

---

outlines/models/openai.py

add fallback tonenizer if tiktoken can not get encoding from model name 
support llm services which provide openai compatibility api such as ollama

add fallback tokenizer

---

docs/reference/models/transformers_vision.md
outlines/generate/api.py
outlines/generate/fsm.py
outlines/generate/regex.py
outlines/generate/text.py
outlines/models/__init__.py
outlines/models/transformers_vision.py
pyproject.toml
tests/generate/test_api.py
tests/generate/test_generate.py

Rendered Docs: https://github.com/lapp0/outlines/blob/multimodal-models/docs/reference/models/transformers_vision.md
- Fixes https://github.com/outlines-dev/outlines/issues/787
- Fixes https://github.com/outlines-dev/outlines/issues/662
- Introduce `models.transformers_vision` which subclasses `models.transformers` and overrides its behavior so it applies, instead of `AutoTokenizer`, `AutoProcessor` to handle the text AND `PIL.Images` media
- Introduce `VisionSequenceGeneratorAdapter`, handling and validating the `media` argument.
- Update `outlines.generate` to dispatch `TransformersVision` models to `VisionSequenceGeneratorAdapter`
- `tests/generate/test_api.py`: Test `prompt` / `media` validation
- `tests/generate/test_generate.py`: 
- Add `model_transformers_vision` fixture. **tests …

Introduce `outlines.models.transformers_vision`

---

outlines/generate/choice.py
outlines/generate/format.py
outlines/generate/fsm.py
outlines/generate/json.py
outlines/generate/regex.py
outlines/generate/text.py
outlines/models/vllm.py
outlines/processors/base_logits_processor.py
outlines/processors/structured.py
tests/generate/conftest.py
tests/generate/test_generate.py

Fixes: `models.vllm` being the only model (other than `models.exllamav2`) using `SequenceGenerator`
- Update `outlines.generate` handlers, default to `SequenceGeneratorAdapter` for all models except `ExLlamaV2Model`
- Update `OutlinesLogitsProcessors` to allow vLLM `input_ids` which are of type `tuple`
- Fix `FSMLogitsProcessor` bug: unable to handle batch sequences where prompt ids are part of `input_ids`. Wasn't caught previously because `model_llamacpp` cannot perform batch generation.
- in `tests/generate/test_generate.py`
- test `model_vllm`
- enable `model_vllm` and `model_transformers_vision` only if cuda is available
Regex logits processing performance has changed in an acceptable manner
- Structured generation with `torch`: `268±7μs` -> `225±1μs`
- Noop with `numpy`: `160±0.9μs` …

Use `outlines.processors` and `SequenceGeneratorAdapter` for `outlines.models.vllm`

---

docs/cookbook/deploy-using-modal.md

memory= parameter is deprecated in favor of size=
See https://modal.com/docs/reference/changelog#062174-2024-05-17
Current doc example produces the following error:
```
/path/test_modal.py:56: DeprecationError: 2024-05-16: The `memory` parameter is deprecated. Use the `size='80GB'` parameter instead.
@app.function(image=outlines_image, gpu=gpu.A100(memory=80))
```

Modal documentation: fix deprecated memory= parameter

---

docs/cookbook/deploy-using-modal.md

It seems modal deletes environment variables, which makes
outlines.models.transformers("mistralai/Mistral-7B-Instruct-v0.2")
fail even after login. This workaround instructs user to manually add
a key before importing the model.
Fixes #1024

Documentation: Fix failing Modal example

---

outlines/models/transformers.py

For some LLM models (such as [chatglm3-6b](https://huggingface.co/THUDM/chatglm3-6b)), the `pad_token_id` is defined as 0 and immutable. We only need to reset for undefined cases.

Fix TransformerTokenizer pad_token_id reset

---

mkdocs.yml

The previous refactor of the `mamba` integration deleted the Mamba documentation file to add the related information to the `transformers` page. This PR redirects the link to the `transformers` page. Fixes #1071.

Fix link to `mamba` model reference

---

pyproject.toml

A license entry in the project metadata makes it easier to detect the license of a project.
Before:
```shell
$ pip install pip-licenses outlines
$ pip-licenses  | grep outlines
outlines                   0.0.46       UNKNOWN
```
After:
```shell
$ pip install .
$ pip-licenses  | grep outlines
outlines                   0.0.47.dev43+g8b78f5d  Apache-2.0
```

Include SPDX license info in project metadata

---

.pre-commit-config.yaml
docs/reference/models/transformers_vision.md
outlines/generate/api.py
outlines/models/transformers_vision.py
tests/generate/test_generate.py
tests/generate/test_integration_transformers_vision.py

Closes https://github.com/outlines-dev/outlines/issues/1076

Make `model_class` required arg, default `processor_class` to `AutoProcessor`

---

docs/cookbook/chain_of_thought.md
docs/cookbook/knowledge_graph_extraction.md
docs/cookbook/qa-with-citations.md
docs/cookbook/react_agent.md

Change cookbook examples: Download model weights in the hub cache folder

Change cookbook examples: Download model weights in the hub cache folder

---

.github/workflows/tests.yml

The matrix ID hash used to produce coverage files isn't being computed.  This PR fixes that.
Also, this changes the tests so that they use development installs, which should help us avoid relative path issues.

Add missing CI matrix step

---

docs/cookbook/deploy-using-modal.md

I updated some of the text of the modal example to add more information on what's happening where, since Modal's general structure may be unfamiliar to new users.
List of changes:
- Removed version constraints on the image. I think this is a questionable choice so I'd love input -- in general, this should probably better be addressed by versioning the docs #999. There's an open PR #1059 here that can help with this too -- I'm happy to revert to pinned versions, or at least update to the current version of outlines (0.0.46).
- Added a brief note that the Mistral model is gated and requires you to request access on HuggingFace.
- Moved the environment variable setting from `import_model` to a `.env` call when the image is created. This is more idiomatic Modal code. It was previously …

Update modal example

---

outlines/models/transformers_vision.py

Fixes https://github.com/outlines-dev/outlines/issues/1123
In a new VLM processor, the text and image arguments are reversed (https://github.com/huggingface/transformers/pull/32473/files#r1734779753). This results in `outlines.models.transformers_vision` passing the arguments to the processor incorrectly.
Pass by kwarg
- CI doesn't run `transformers_vision` tests because they require GPU. Tests for `transformers_vision` pass locally, however.
- CI was run while huggingface.co was experiencing instability, 3.8 passed, 3.10 failed due to a failure to retrieve a tokenizer.

Pass `text` and `images` as kwargs to VLM processor

---

tests/fsm/test_regex.py
tests/generate/test_integration_llamacpp.py

These changes address an issue caused by a recent update to the `NousResearch/Hermes-2-Pro-Llama-3-8B` config.

Set the tokenizer versions in `test_create_fsm_index_tokenizer`

---

outlines/types/airports.py
pyproject.toml

Fixes https://github.com/dottxt-ai/outlines/issues/1093
`pyairports` is unmaintained and often breaks `pip install outlines`. It's also out of date.
This PR replaces it with the more recently maintained and working package [airportsdata](https://github.com/mborsetti/airportsdata/)

Remove Broken pyairports Package, Replace with airportsdata

---

docs/reference/index.md
docs/reference/models/models.md
docs/reference/models/openai.md
docs/reference/text.md
examples/babyagi.py
examples/math_generate_code.py
examples/meta_prompting.py
examples/pick_odd_one_out.py
examples/react.py
examples/self_consistency.py
outlines/generate/choice.py
outlines/generate/json.py
outlines/models/openai.py
pyproject.toml
tests/models/test_openai.py

[Rendered Docs](https://github.com/dottxt-ai/outlines/blob/6066b367acf7698e218a3f51db16a18bf15e1eb3/docs/reference/models/openai.md#structured-generation-support)
- Closes https://github.com/dottxt-ai/outlines/pull/1060
- Fixes https://github.com/dottxt-ai/outlines/issues/1086
- Fixes https://github.com/dottxt-ai/outlines/issues/370
`tokenizer` was removed as a requirement for `models.openai` because the logit bias filter no longer needs to be constructed.
This has the side effect of fixing a number of issues users were having with using arbitrary OpenAI-compatible endpoints.
Verified by author of https://github.com/dottxt-ai/outlines/issues/1135 and in a brief smoke test at the bottom of this description.
- Fixes https://github.com/dottxt-ai/outlines/issues/326
- Fixes …

Integrate OpenAI API Structured Generation

---

outlines/generate/api.py
tests/generate/test_generate.py

Fixes https://github.com/dottxt-ai/outlines/issues/1109
Logits processors can't be reused across multiple generation runs and must be copied. `SequenceGeneratorAdapter` wasn't respecting this requirement. The result is that in `generator = generate.choice(...)`, the `generator` can only be used once.
During inference, logits processors are called with a sequence of `input_ids + output_ids`. Since structured generation only applies to `output_ids`, we track the length of `input_ids` on the first call and treat subsequent tokens as `output_ids`. However, this approach fails when the `input_ids` sequence changes.
`copy` the logits processors for each `SequenceGeneratorAdapter.__call__(...)`, ensuring they can correctly determine the start of `output_ids`.
Logits processors requires more …

Don't re-use logits processors in SequenceGeneratorAdapter, copy them

---

outlines/prompts.py

I really like the `@outlines.prompt` decorator. However, I noticed it is slow when formatting a large number of examples. The main inefficiency is creating the Jinja environment for every call of `render`. This PR makes a minor change to re-use the same Jinja environment per prompt. 
Note: This makes the `render` function obsolete. However, I kept it for backwards compatibility. Please advise if this should be further refactored.
Small benchmark to test it:
```py
import timeit
import outlines
@outlines.prompt
def test_tpl(variable):
"""{{variable}} test"""
print('Formatted template:', test_tpl(variable='this is a'))
def test_render():
test_tpl(variable='this is a')
execution_time = timeit.timeit(test_render, number=1000)
print(f"Execution time for 1000 runs: {execution_time} seconds")
``` …

Reuse jinja environment for a prompt

---

docs/reference/models/exllamav2.md
outlines/generate/cfg.py
outlines/generate/fsm.py
outlines/generate/regex.py
outlines/generate/text.py
outlines/models/exllamav2.py
pyproject.toml
tests/generate/conftest.py
tests/generate/test_generate.py
tests/generate/test_integration_exllamav2.py

@isamu-isozaki did a great job implementing a fully functioning `outlines.models.exllamav2`. This PR introduces minor fixes and a documentation update. 
This PR rebases with main and squashes his commits into one: https://github.com/dottxt-ai/outlines/commit/d1f5609b2ac25b47aa01ffbe98d4d2f70317475c
- All changes noted in core functionality PR: https://github.com/dottxt-ai/outlines/pull/1010
- Automatically download necessary models for tests to run successfully
- Make OutlinesExLlamaV2Tokenizer, which is compatible with cfg
- For `models.exllamav2` enable `generate.cfg` and `generate.fsm`
- Document how to install third party ExLlamaV2 with logits processor functionality
- closes https://github.com/dottxt-ai/outlines/pull/1010 (original PR)
- Fixes …

Minor Changes on Top of Isamus EXL2 PR (Docs, Enable FSM/CFG, Fix Tokenizer)

---

.github/workflows/publish_documentation.yml
mkdocs.yml
requirements-doc.txt

Fixes https://github.com/outlines-dev/outlines/issues/999
Versions the documentation using `mike`.
Demo: 
- Site: https://lapp0.github.io/outlines/
- Branch: https://github.com/lapp0/outlines/tree/gh-pages
Behavior:
- Doesn't backfill documentation versioning.
- Has drop-down for version history, including all versions starting with the next release
- Version dropdown: "main / unstable", followed by "[latest version number] / stable", followed by all prior versions
- `/` redirects to `/stable`
- **breaks any external links to documentation**
- e.g. https://outlines-dev.github.io/outlines/reference/json_mode/ is now https://outlines-dev.github.io/outlines/latest/reference/json_mode/
**Must have https://github.com/outlines-dev/outlines/settings/pages set to "deploy from a branch" with …

Version the Documentation

---

README.md
docs/cookbook/simtom.md
outlines/fsm/guide.py
outlines/models/exllamav2.py

Example:
- Broken: https://dottxt-ai.github.io/outlines/reference/prompting/
- Fixed: https://dottxt-ai.github.io/outlines/latest/reference/prompting/
Note: https://dottxt-ai.github.io/outlines/ is valid, as it redirects to `outlines/latest/`

Fix Broken Docs Links

---

mkdocs.yml

use `dottxt-ai/outlines` not `outlines-dev/outlines` in mkdocs

---

benchmarks/bench_json_schema.py
benchmarks/bench_regex_guide.py
outlines/fsm/guide.py
outlines/fsm/parsing.py
outlines/processors/structured.py
pyproject.toml
tests/fsm/test_guide.py
tests/fsm/test_parsing.py
tests/generate/test_integration_llamacpp.py
tests/generate/test_integration_transformers.py

Necessary changes to use `outlines-core==0.1.14`
- `fsm_union`, `walk_fsm`, and `get_sub_fsms_from_seq` were missing from `outlines/fsm/parsing.py`, breaking CFG. We include it once again
- pin to `outlines-core==0.1.14`, which includes wheels and removes the requirement for a rust compiler to install.
- Fixes https://github.com/dottxt-ai/outlines/issues/1198
- Fixes https://github.com/dottxt-ai/outlines/issues/1202
- Update `RegexGuide` to conform to to `outlines-core`
- make `torch` a default requirements
- Fixes https://github.com/dottxt-ai/outlines/issues/1197

Compatibility updates for next `outlines-core` release

---

outlines/base.py
pyproject.toml

Check the numpy major version number before deciding which file to import methods from.
I have not benchmarked numpy 1 vs numpy 2 performance for outlines, but I have verified that outlines works as intended when using numpy 2 for the examples in the README.
Closes https://github.com/dottxt-ai/outlines/issues/1104

Add compatibility for numpy 2 while preserving numpy 1 compatibility

---

outlines/models/mlxlm.py
pyproject.toml
tests/models/test_mlxlm.py

Updated to match the latest version of mlx-lm (and updated requirements to mlx-lm>=0.19.2)
Also wrote a short test file.
See this commit in mlx-lm where the KVCache was updated: https://github.com/ml-explore/mlx-examples/pull/1015
This fixes #1225

Updated mlx-lm kvcache creation

---

examples/beam-cloud/README.md
examples/beam-cloud/app.py

This PR shows an example of deployment an outlines API to beam.cloud.

add beam.cloud deployment example

---

outlines/models/__init__.py

This is tiny, and I might be wrong in case `OpenAI` (since it's basically an API wrapper) is in fact NOT a `LogitsGenerator`.
But adding it seems logical, and I want it to be in there for my use case (which is that I have a function that creates a model, and with this change I can specify the return type to be `LogitsGenerator`).

Add OpenAI to LogitsGenerator

---

docs/cookbook/extract_event_details.md
docs/cookbook/extract_event_details.py
mkdocs.yml

If useful, an example to illustrate how to extract event details from a message like :
```
Hello Kitty, my grandmother will be here , I think it's better to postpone our
appointment to review math lessons to next Friday at 2pm at the same place, 3 avenue des tanneurs, 
I think that one hour will be enough
see you 😘 
```
to 
```json
{
"title":"Math lessons",
"location":"3 avenue des tanneurs",
"start":"2024-11-22T14:00:00Z"
}
```
Indeed, the next Friday is the 22 November, the smallest models cannot infer relative date like this example of ‘next Friday’ with precision and a real benchmark would be welcome, or maybe another approach with a function call
Btw, moving the python code in a dedicated file allow to benefit of the precommit hooks and homogenous code
In the future, it may also …

Cookbook receipe on extract event details from text

---

benchmarks/bench_processors.py
outlines/processors/base_logits_processor.py
pyproject.toml
tests/processors/test_base_processor.py

This PR adds a JAX compatible API, refer issue #1027 
Looking forward for review and open to feedback(especially in writing tests).

Add jax compatible api

---

README.md
outlines/fsm/json_schema.py
outlines/generate/json.py
tests/fsm/test_json_schema.py
tests/generate/test_integration_transformers.py

Add json call with multi-function enums

---

docs/reference/models/llamacpp.md
docs/reference/models/mlxlm.md
docs/reference/models/openai.md
docs/reference/models/transformers.md
docs/reference/models/vllm.md
outlines/models/transformers.py
outlines/models/vllm.py
pyproject.toml
tests/generate/test_integration_transformers_vision.py

Users are currently running into install issues. After a clean install of `outlines` they get an error message that asks for `transformers` to be installed. This should not be the case, as the library is not required for every integration. In this PR we remove `transformers` and `datasets` top-level imports, and add per-integration optional dependencies.
Supersedes #1295.  Fixes #1263.

Fix library top-level imports

---

pyproject.toml

Fixes #1314
A few important guidelines and requirements before we can merge your PR:
Consider opening a **Draft PR** if your work is still in progress but you would
like some feedback from other contributors.
[issues]: https://github.com/dottxt-ai/outlines/issues
[git-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[docstring-guidelines]: https://numpydoc.readthedocs.io/en/latest/format.html

Fix typo in vllm extra requirements

---

.gitignore
README.md
outlines/generate/choice.py
tests/generate/test_generate.py

This PR aims at solving #1218 (requires #1277 to be merged)
Quick fix to solve #1275

Handle enum in choice

---

pyproject.toml

Include the outlines-core fix (https://github.com/dottxt-ai/outlines-core/pull/123) to this issue: https://github.com/dottxt-ai/outlines-core/issues/122.
Currently, `pip install outlines==0.1.9` is causing vLLM's ARM CPU container to fail to build.

Bump outlines-core version to 0.1.26

---

docs/cookbook/receipt-digitization.md

The current link points to a HTML instead of a PNG, so after it's downloaded via requests.get, PIL isn't able to recognize the format and rightly so.

Fix image link in receipt-digitization example

---

outlines/generate/api.py
outlines/samplers.py
tests/test_samplers.py

This PR addresses #1335 
I have kept the `SamplingParameters` in `outlines/generate/api.py`  cause its imported at many places and may break examples ig. 
Would you want to change that @dgerlanc ??
Otherwise if this looks good, I can make docs changes if needd, lmk.

Move generation of sampling params

---

mkdocs.yml

Hi, Thank you for this great library!
It seems that the docstrings are not rendered correctly in the docs. I think we should explicitly set the `docstring_style` because [it defaults to `"google"`](https://mkdocstrings.github.io/python/usage/configuration/docstrings/#docstring_style) but outlines is using numpy.
Before:
After:
There seem to be other issues in the docstrings:
- for example [`Properties`](https://github.com/dottxt-ai/outlines/blob/main/outlines/models/openai.py#L23) should be [`Attributes`](https://numpydoc.readthedocs.io/en/latest/format.html#parameters)
- only openai and transformers models are present in the [api reference](https://github.com/dottxt-ai/outlines/blob/main/docs/api/models.md) 
I'm happy to make followup PRs for those.
Please let me know if I missed …

Set docs `docstring_style`

---

docs/reference/models/transformers.md
mkdocs.yml

Also, clicking the `Mamba` title at left now directly jumps to the Mamba section (improving UX).

Fix docs TOC & NAV issues for `mamba` and `transfomers`

---

benchmarks/bench_processors.py
outlines/processors/structured.py

While debugging #1282, I found the the issue to be caused by `non_blocking=True` on a Mac with an MPS device.
The usage of `non_blocking=True` is only safe for CPU->GPU, as far as I understand from [this guide](https://pytorch.org/tutorials/intermediate/pinmem_nonblock.html#other-copy-directions-gpu-cpu-cpu-mps).
For other directions, especially CPU->MPS in my case, this results in a all-zero vector instead of the real token ids which generates wrong tokens and results in errors like described in #1282.
I also tried to use `torch.mps.synchronize()`, but it doesn't help.
I'm haven't benchmarked the difference in speed, but I suspect it to be neglectable because the created vector is accessed [directly afterwards](https://github.com/dottxt-ai/outlines/blob/36f1bf27a80f5877b88a915749341664cef …

Fix GuideLogitsProcessor for MPS device

---

pyproject.toml
tests/conftest.py
tests/generate/test_integration_vllm.py

Skip `vllm`-related tests on non-linux platforms

---

docs/cookbook/chain_of_thought.md

- Replace `outlines.integrations` import with import from `outlines.fsm.json_schema` (#1061) 
- Fix `build_regex_from_schema` to import from `outlines_core` instead of `outlines` (#1311)

Fix `json_schema` imports in cot example

---

docs/cookbook/react_agent.md

the old library structure has not been updated to reflect the present one. now the example will work.

Update react_agent.md with current import structure

---

docs/reference/models/transformers_vision.md

`transformers` maintainer here 👋 
Was trying out your `transformers_vision` example, and ran into a bug in the example. In a nutshell, the original demo prompted the model with 3 images, but only two were being passed.
<details>
<summary>Stand-alone script for reproduction, based on the example:</summary>
```py
import outlines
from transformers import LlavaNextForConditionalGeneration
import torch
model = outlines.models.transformers_vision(
"llava-hf/llava-v1.6-mistral-7b-hf",
model_class=LlavaNextForConditionalGeneration,
)
from PIL import Image
from io import BytesIO
from urllib.request import urlopen
def img_from_url(url):
img_byte_stream = BytesIO(urlopen(url).read())
return Image.open(img_byte_stream).convert("RGB")
description_generator = outlines.generate.text(model)
foo = …
```

[docs] Fix `transformers_vision` multiple Images example

---

tests/conftest.py

Before this commit, when you ran `pytest -k specific_test`, it spawned dozens of the same skipped warnings message on stdout... IMHO, that was not ideal ^^
Bug introduced in d32dfde3ae7eac71f57af96d5141975ef9322b12, see previous PR https://github.com/dottxt-ai/outlines/pull/1357

Fix `vllm`-related pytest warning (that was spaming user)

---

outlines/prompts.py
tests/test_prompts.py

Allow giving custom filters to the prompt decorator
```
def reverses: str) -> str:
return s[::-1]
@prompt(filters={ 'reverse': reverse })
def reverse_prompt(text):
'''{{ text | reverse }}'''
prompt = reverse_prompt("Hello")
print(prompt)
>>> "olleH"
```

add filters to prompt function

---

docs/reference/models/models.md

There's an extra `outlines.generate` row in the feature matrix docs. This removes it.
I also modified the markdown syntax for one header to use ** rather than __, consistent with the rest of the table.

Remove incorrect text from feature matrix docs

---

outlines/processors/base_logits_processor.py
tests/processors/test_base_processor.py

We have noticing the following error with a recent version of outlines when used with MLX:
```
TypeError: argument 'token_id': 'float' object cannot be interpreted as an integer
At:
/.../outlines_core/fsm/guide.py(294): get_next_state
/.../outlines/processors/structured.py(101): process_logits
/.../outlines/processors/base_logits_processor.py(90): __call__
```
The issue is that the MLX array of tokens, which are integers, are being force-converted to floats, even though outlines expects an integer array. This is because all MLX arrays are being converted to `float32`, even when it's not necessarily appropriate, like in this case. Looking at the [commented link](https://ml-explore.github.io/mlx/build/html/usage/numpy.html#pytorch), the advice was to convert to `float32` only for …

[MLX] [bugfix] Preserve dtype of array when converting to torch

---

.editorconfig
.gitignore
.pre-commit-config.yaml
.pydocstyle
.vscode/settings.json
outlines/fsm/types.py
outlines/processors/base_logits_processor.py
pyproject.toml

WDYT about Astral’s tools, [Ruff](https://docs.astral.sh/ruff/) and [uv](https://docs.astral.sh/uv/)?

Add a few dotfiles to improve newcomers' experience

---

.devcontainer/devcontainer.json
pyproject.toml

[DevContainer](https://code.visualstudio.com/docs/devcontainers/create-dev-container) is a great tool for providing a one-click development environment for new contributors. It works seamlessly through the GitHub interface _(with [GitHub Codespaces](https://github.com/features/codespaces))_ or locally with tools like VSCode or JetBrains’ built-in plugins. Maybe, DevContainer can help achieve a basic level of reproducibility between the CI and local development environments, e.g., the `devcontainer` CLI could be integrated into GitHub Actions?

Add DevContainer configuration file

---

.github/workflows/tests.yml
pyproject.toml
tests/generate/test_generate.py
tests/models/test_openai.py

Tests are currently failing on branch v1.0, which is detrimental to visibility on whether the change proposed by our PRs to this branch are causing new test failures.
4 fixes:
- Add the package `datasets` as a dependency
- Skip tests marked as "api_call" in the CI
- Provide a mock api key value to the OpenAI client in tests that do not make actual api calls (otherwise it causes an error when initializing the client)
- Temporarily remove `LlamaCpp` from the list of model fixtures on which we run the generate tests as the refactored models are incompatible with those tests. On this topic, do you think it's fine to remove the models as we refactor them and then to completely rewrite the generate tests @rlouf (I would create an issue for that and add it to the v1.0 milestones)?

Fix the failing tests on branch v1.0

---

outlines/generate/__init__.py
outlines/models/llamacpp.py
outlines/types/__init__.py
tests/test_types.py

This PR addresses issue #1300 
We create a new type `CFG` and update the `Generator` class to accept the `CFG` type (creating a `CFGLogitsProcessor`) on top of accepting regex-based types (creating a `RegexLogitsProcessor`)

Create the CFG type to be used as an output type

---

outlines/models/__init__.py
outlines/models/anthropic.py
outlines/models/base.py
outlines/models/gemini.py
outlines/models/llamacpp.py
outlines/models/openai.py
tests/models/test_anthropic.py
tests/models/test_gemini.py
tests/models/test_llamacpp.py
tests/models/test_openai.py

Updated on 2025-02-11
The objective of this PR is to create a base class all models would inherit from. This base class defines the interface for models and includes a `__call__` method that allows models to be called with a prompt and output type directly following the suggestion in #1359 .
Formatting methods for the input and output types are implemented in a separate class inheriting from the base class `ModelTypeAdapter`. Each model must set a `type_adapter` attribute in its initialization. The rationale for separating those from the model class is that the accepted types for each model and the formatting logic are quite different concerns compared to the specifics of the model's implementation. Separating them also allows us to have an easier to read documentation of the accepted …

Create a base class for the models

---

flake.lock
flake.nix
pyproject.toml
shell.nix
uv.lock

This PR is a draft aimed at producing a reproducible Python virtual environment. `uv` seems like the right tool for this because it has a lock file mechanism _(but we could alternatively use `poetry`)_, and `nix` would be my preferred choice for managing system dependencies _(I’m not aware of many alternatives for pinning system dependencies, apart from possibly using a container with a pinned version of Alpine Linux?)_
This is still a draft, the `shell.nix` is currently too convoluted _(and ultimately I would like to rather rely on [uv2nix](https://github.com/dottxt-ai/outlines/pull/1368#issuecomment-2586566084))_, and the goal of this PR is to enable the use of this environment in GitHub Action jobs! Using this setup in CI would help avoid non-reproducible issues, such as [this …

Reproducible Python virtual environment using `uv` and `nix`

---

outlines/caching.py

Make cache dir more robust.
We observed that when starting a docker container with a non existing user inside the container (using -u) outlines would try to use /.cache/ as a cache directory which will give permission denied. This PR sets an order of preference for finding the cache home uses XDG_CACHE_HOME if available and OUTLINES_CACHE_DIR is not set.

Fix cache dir, make it more robust when there is no $HOME

---

docs/api/models.md
docs/community/contribute.md
outlines/models/exllamav2.py
outlines/models/llamacpp.py
outlines/models/mlxlm.py
outlines/models/openai.py
outlines/models/transformers.py
outlines/models/transformers_vision.py
outlines/models/vllm.py
outlines/prompts.py

Follow up of #1343
In this PR I added:
- all models to the API reference (we had only openai and transformers before)
- fixes to the docstrings that were not following the numpy style
- fixes to docstrings wrongly rendered by mkdocstring
Thanks :)

Various docs fixes

---

docs/overrides/home.html

This PR adds a link in the docs to the social media profile of dottxt on the Bluesky social network alongside the existing link to the profile on X.
Preview of built docs:

Add Bluesky social media profile link to docs

---

docs/reference/models/dottxt.md
outlines/models/__init__.py
outlines/models/dottxt.py
pyproject.toml
tests/models/test_dottxt.py

This PR addresses issue #1411 
We add Dottxt as a new type of Outlines model.
Similarly as in PR #1415, there may be a decision to take regarding the naming of the `Generator` classes (and of the associated model type lists). Here I created a new `Generator` class called `CompiledAPIGenerator`. The reason for this addition is that we need a kind of generator that adds a step during initialization during which we rely on the model for compiling the output type into what the model will eventually use for generation. I tried to make it general so that it could fit other new models if some were to follow the same logic.
An alternative that would have allowed us not to create a new generator class would have been to use the existing `APIGenerator` and to put the output type compilation step in …

Add integration with Dottxt

---

outlines/generate/__init__.py
outlines/models/__init__.py

Addresses issue #1423
I think `Steerable` is good. I was looking for an antonym and came up with `Enclosed`. Other candidates I considered are `Sealed` and `Locked`.

Rename Local/API into Steerable/BlackBox for models/generators

---

outlines/models/mlxlm.py
outlines/models/openai.py
outlines/processors/base_logits_processor.py
tests/models/test_mlxlm.py

Addresses issue #1292 
Modify the `MLXLM` class to inherit from the base `Model` class and implement the standard interface of models for the v1.0.
A noteworthy change here is in the method `OutlinesLogitsProcessor.__call__`. The `mlx-lm` library gives to the logits processor the logits in 2D even though there's a single prompt (so input_ids are 1D). As this was causing a bug (the logits processor expect those 2 variables to have the sameshape), I added an `if` statement at the start of the method to make the input_ids 2D when encountering this situation.

Refactor the MLXLM model

---

outlines/generator.py
outlines/models/anthropic.py
outlines/models/base.py
outlines/models/dottxt.py
outlines/models/gemini.py
outlines/models/llamacpp.py
outlines/models/mlxlm.py
outlines/models/ollama.py
outlines/models/openai.py
outlines/models/transformers.py
outlines/models/vllm.py
tests/models/test_anthropic.py
tests/models/test_dottxt.py
tests/models/test_gemini.py
tests/models/test_llamacpp.py
tests/models/test_mlxlm.py
tests/models/test_openai.py
tests/models/test_transformers.py
tests/models/test_vllm.py

Addresses issue #1482 
This PR aims at standardizing the use of streaming in our models and at aligning it on the functioning of the regular text generation. 3 changes:
- Add a `generate_stream` abstract method to the `Model` parent class and implement it in all models
- Add a `stream` method to the `Generator` classes that invokes the `generate_stream` method of the underlying model
- Add a `stream` method to the `Model` parent class that creates a `Generator` and then invokes its `stream` method
Thus, we end up having exactly the same system as with the `__call__` and `generate` methods for regular text generation.
It also modifies the models' tests.

Add stream method to Generator and Model classes

---

outlines/generate/json.py

Running the example from the docs with OpenAI model raises a schema error in the API. Fixing this error might also address #1376 because the vendor has introduced Structured Generation which is mostly compatible with this library.
```
from pydantic import BaseModel
from outlines import models, generate
class User(BaseModel):
name: str
last_name: str
id: int
model = models.openai("gpt-4o-mini")
generator = generate.json(model, User)
result = generator("Create a user profile with the fields name, last_name and id.")
```
This causes an error in the API:
```
Traceback (most recent call last):
File "/Users/frederikfix/src/konvenit/odin/scratch/mytest.py", line 55, in <module>
result    = generator("Create a user profile with the fields name, last_name and id.") …
```

JSON schema error when using OpenAI with Pydantic model

---

.github/ISSUE_TEMPLATE/bug_report.yml

The way these commands show up when a user fills out a new bug report is misleading, as they all get mashed into one line.
Copy-pasting this results in only the first command running, which is presumably not what the template author intended.

Tweak version commands in bug_report.yml

---

docs/reference/models/transformers_multimodal.md
outlines/models/transformers.py

Addresses #1304 
The objective of this PR is to allow users to provide a wider range of possible inputs to a `TransformersMultiModal` model. The rationale behind it is that we want users to be able to use the class with as many models/generators as possible (for instance video) without having to explicitly cover this use case in the type adapter.
Overall, this change removes some safeguards on the model input to give more freedom to the end user. I think this is justified by the fact that multimodal transformers models are an advanced use case for which it's hard for us to anticipate all needs of users.

Modify TransformersMultiModalTypeAdapter to make it more flexible

---

outlines/processors/guide.py
tests/processors/test_guide.py

Addresses issue #1466 
Caching for the creation of the states mapping in the `RegexGuide` was removed in PR #1278 to address issue #1274 highlighting that the cache is causing an error.
As I cannot reproduce the error with the v1.0 branch of Outlines using `outlines_core==0.1.26`, I propose we simply restore the cache on the function `cached_create_states_mapping` (and add tests for it).

Restore index caching

---

outlines/generator.py
outlines/models/base.py
outlines/models/llamacpp.py
outlines/models/mlxlm.py
outlines/models/tokenizer.py
outlines/models/transformers.py
outlines/models/vllm.py
outlines/processors/base_logits_processor.py
outlines/processors/structured.py
outlines/processors/tensor_adapters/__init__.py
outlines/processors/tensor_adapters/base.py
outlines/processors/tensor_adapters/jax.py
outlines/processors/tensor_adapters/mlx.py
outlines/processors/tensor_adapters/numpy.py
outlines/processors/tensor_adapters/tensorflow.py
outlines/processors/tensor_adapters/torch.py
outlines/serve/serve.py
pyproject.toml
tests/models/test_llamacpp.py
tests/models/test_mlxlm.py
tests/models/test_transformers.py
tests/models/test_transformers_multimodal.py
tests/models/test_vllm.py
tests/processors/test_base_processor.py
tests/processors/test_guide.py
tests/processors/test_structured.py
tests/processors/test_tensor_adapters.py
tests/test_generator.py

This PR addresses issue #1445 
The PR creates classes of type `TensorHandler` for various tensor libraries. Such classes are used by the logit processors to avoid having to manipulate the `input_its/logits` tensors itself. This solution allows us not to require the user to download all tensor libraries supported by outlines and to treat the tensor in their native type without having to turn them into torch tensors. We also modify the local models to possess an attribute `tensor_library_name` to indicate to the logits processor what `TensorHandler` implementation to use.
Thanks to those change, we remove the mandatory dependencies on torch and numpy.

Add library specific handling of tensors in logits processors

---

outlines/models/openai.py
tests/models/test_openai.py

Addresses issue #1511 
There was an issue with the OpenAI model: it was returning one completion regardless of what was received from the client. This PR changes it such that the model returns as many completions as it gets.

Allow the OpenAI model to return multiple completions

---

outlines/v0_legacy/generate/json.py

This PR adapts what's proposed in #1515 to the v1.0 branch. We replace the deprecated `parse_raw` method of `pydantic` by `model_validate_json`

Replace parse_raw by model_validate_json

---

outlines/processors/tensor_adapters/base.py
outlines/processors/tensor_adapters/mlx.py

As the `allowed_tokens` returned by the `guide` object coming from outlines-core, we need to ensure the `full_like` and the `concatenate` methods of tensor handlers can handle torch tensors as those `allowed_tokens` are passed as arguments to them. This was already the case for all tensor adapters except `mlx`.
In the future, we need to look at upgrading `outlines-core` to be able to fully remove the dependency on `torch`

Fix errors in the mlx tensor adapter

---

README.md

Add commercial info to the v1 docs

---

outlines/models/llamacpp.py
outlines/models/openai.py
outlines/models/vllm_offline.py
outlines/v0_legacy/function.py
outlines/v0_legacy/generate/cfg.py
outlines/v0_legacy/generate/choice.py
outlines/v0_legacy/generate/format.py
outlines/v0_legacy/generate/fsm.py
outlines/v0_legacy/generate/json.py
outlines/v0_legacy/generate/regex.py
outlines/v0_legacy/generate/text.py
outlines/v0_legacy/models/exllamav2.py
outlines/v0_legacy/models/llamacpp.py
outlines/v0_legacy/models/mlxlm.py
outlines/v0_legacy/models/transformers.py
outlines/v0_legacy/models/transformers_vision.py
outlines/v0_legacy/models/vllm_offline.py

After talking about it, we decided we should remove those deprecated features sooner so we don't have to deal with them for so long.

Change the deprecation warning of v0 from v1.5.0 to v.1.1.0

---

mkdocs.yml

Redirects the blog to blog.dottxt.co, rather than use the one in our docs. This is also addressed for the v1 docs in #1529.

Make docs "blog" link to blog.dottxt.co

---

outlines/applications.py
tests/test_applications.py

Addresses #1576 
I propose to have users put their template args in a dict instead of their inference kwargs because the list of the template variables is fixed while they may want to add/remove optional inference parameters.
A consequence of this change is that users cannot provide template variables as positional arguments as they used to be able to if the template was a callable, but I think it's for the best.

Modify Application's call method to include inference kwargs

---

outlines/models/gemini.py
pyproject.toml
tests/models/test_gemini.py
tests/models/test_gemini_type_adapter.py

Addresses #1581 
This PR modifies the `Gemini` model to take a `google.genai.Client` instance as an argument instead of a `google.generativeai.GenerativeModel` instance. It modifies the methods of the model to adapt to the interface of the new client and updates the tests acordingly. A notable change is that the model and its loader function now have an optional `model_name` parameter.
I have not updated the documentation as it's handled by this ongoing PR #1577

Update the Gemini model to use their new sdk

---

outlines/models/transformers.py

A `print` statement was committed by mistake in the the code for the `Transformers` model. This PR is removing it.

Remove mistakenly committed print statement

---

outlines/models/__init__.py
outlines/models/sglang.py
tests/models/test_sglang.py
tests/models/test_sglang_type_adapter.py

I realized that the g is capitalized in the name of this library, so we should rename our model to follow their spelling.

Rename SgLang into SGLang

---

outlines/types/__init__.py
outlines/types/dsl.py
tests/types/test_dsl.py

This is the equivalent of #1532, but merging into v1 instead of main as the latter's tests are currently broken.

Restore deprecated regex DSL functions with a warning

---

docs/guide/getting_started.md

This PR fixes minor typos found in the getting started documentation to improve readability and code examples.
- **Line 74**: Fixed "Context-free Grammarq" to "Context-free Grammars" in the output types section
- **Multiple Choice example**: Fixed missing closing quote in enum definition: `pizza = "pizza"`, `burger = "burger"`
These are minor documentation improvements that fix typos and ensure code examples are properly formatted. The changes maintain the original meaning while correcting syntax errors.
This is my first contribution to this project, but I wanted to make a small contribution by fixing this typo to help improve the project. 😊

Fix typos in getting started guide

---

.github/workflows/tests_nightly.yml

Closes #1634 
The Slack action was causing an error because of GitHub Enterprise restrictions. Slack notification is not that important as we're receiving an email anyway. We can always look into it in more details in the future to add it back, but in the short term we should first have the workflow run.

Fix nightly tests (remove Slack alert causing troubles)

---

docs/examples/index.md
docs/guide/getting_started.md

This PR removes a dead link to the VLM example from the [examples/index.md](https://github.com/dottxt-ai/outlines/blob/main/docs/examples/index.md). The original example has since been moved to the guides section, as documented in https://github.com/dottxt-ai/outlines/pull/1643.
My only open question is whether the example should still be referenced in the examples index (as a walkthrough-style example). Happy to follow the maintainers' guidance on this.

Remove dead link to VLM example from examples index

---

pyproject.toml

When building an outlines wheel (e.g. `python -m build .`), we see this warning:
```
############################
############################
Python recognizes 'outlines.fsm' as an importable package[^1],
but it is absent from setuptools' `packages` configuration.
This leads to an ambiguous overall configuration. If you want to distribute this
package, please make sure that 'outlines.fsm' is explicitly added
to the `packages` configuration field.
```
The ambiguity of the configuration means that wheel build tools such as `pip wheel` can choose to exclude submodules (such as `outlines.fsm`) when creating the wheel. When we've been creating the wheel, we see that `outlines.fsm` -- or any other outlines python submodule -- is not packaged within the wheel.
The fix in the PR is based off the …

Fix broken wheel builds caused by ambiguous packaging instructions

---

docs/features/advanced/backends.md
outlines/backends/xgrammar.py
tests/backends/test_xgrammar.py

Closes #1698 
This is a dependency for adding support for thinking models (#1627) as we will need to add some custom logic to the logits prorcessor, so we must create our own.
The PR adds supports for `mlx` but not for `numpy` (so the `LlamaCpp` model is not supported) as it does not seem that Xgrammar currently supports `numpy` tensors. If that changes in the future or if we find a way to make it work, it should be easy to add as the logits processor already has the right architecture for it.
PS: coverage check is still broken, there's an issue for that we should work on at some point

Create our own logits processor for Xgrammar, add support for mlx

---

outlines/backends/llguidance.py
outlines/backends/outlines_core.py
outlines/backends/xgrammar.py

Edited 2025-08-07
Closes #1710 
The problem described in the issue concerned the `Transformers` models using `torch` tensors and running on a non-cpu device. The issue was a mismatch between the location of the logits and that of the bitmask.
The solution is to properly handle the device location of the bitmasks before calling the `apply_token_bitmask_inplace` functions.

Fix bug related to the device of the bitmasks and logits for torch

---

outlines/backends/outlines_core.py

Deals with the consequences of an [issue in outlines-core](https://github.com/dottxt-ai/outlines-core/issues/227)
As described in the linked issue, there is a bug in outlines-core in which, when in a final position, the `eos_token_id` is returned by the `get_tokens` method, but then causes an error if we try to advance through the guide with it! To avoid this problem, the outlines implementation used to simply check whether the current state is final, and stops advancing through the guide if that's the case. That causes another problem in case there are several different final states in the index, as we were not advancing through the guide even though a token leading to another final state was generated.
The fix proposed here is to check whether the token last generated is accepted by the …

Fix a bug in OutlinesCore backend about advancing when in final state

---

docs/features/models/transformers_multimodal.md
outlines/inputs.py
outlines/models/transformers.py
tests/models/test_transformers_multimodal.py
tests/models/test_transformers_multimodal_type_adapter.py
tests/test_inputs.py

This PR improves the handling of **multimodal** chat inputs for TransformersMultiModal models. It addresses the challenge of correctly applying chat templates to text while integrating diverse media assets (images, audio, video).
-   **`outlines/models/transformers.py`**:
*   Refactored `format_chat_input` to explicitly separate multimodal assets (images, audio, video) from text messages within chat inputs;
*   Ensured that the complete `Chat` messages are passed to `self.tokenizer.apply_chat_template` to generate text prompts with correct placeholders for multimodal content;
-   **`docs/features/models/transformers_multimodal.md`**:
*   Updated documentation to reflect the new multimodal chat input handling capabilities;
*   Added a new usage example demonstrating how to utilize these …

Fix correct handling of chat multimodal inputs in TransformersMM class
